<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\AFSLib-main\AFSLib\AFSLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kid.Script\Kid.Script.csproj" />
  </ItemGroup>
</Project>
