ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinFrameType(1)
ScrBgmStop(180)
ScrChrDel(0)
ScrChrSet(5, 28708)
ScrUpDateImage(90, 13)
ScrWaitTime(90)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 13)
ScrChrSet(5, 27272)
ScrJumpR(0x0002)
ScrBgmPlay(28770, 1)
ScrWaitIcon(1)
ScrWinFrame(1)
ScrMess(412, 0, "", "夜が明けても、目が冴えて眠れない。")
ScrWaitKey()
ScrWinClear()
ScrMess(413, 0, "", "理由は明確だったが、<cr>どうすることも出来なかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(414, 0, "", "手の中にある通信機を指でなぞりながら、<cr>有里の冷たい顔を思い出す。")
ScrWaitKey()
ScrWinClear()
ScrMess(415, 0, "", "何度も思い出すのは、俺が後悔しているからなのか。")
ScrWaitKey()
ScrWinClear()
ScrMess(416, 0, "", "好きだとは言えなかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(417, 0, "", "俺たちには自分の気持ちより<cr>優先しなければならない仕事がある。")
ScrWaitKey()
ScrWinClear()
ScrMess(418, 0, "", "間違ってはいないはずだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(419, 0, "", "俺は間違っていない。")
ScrWaitKey()
ScrWinClear()
ScrMess(420, 0, "", "間違っていない！")
ScrWaitKey()
ScrWinClear()
ScrSePlay(280, 0)
ScrMess(421, 0, "", "ピ……")
ScrWaitKey()
ScrWinClear()
ScrMess(422, 21441, "修史", "「？」")
ScrWaitKey()
ScrWinClear()
ScrMess(423, 0, "", "手元の赤いランプがつく。")
ScrWaitKey()
ScrWinClear()
ScrChrSet(4, 28215)
ScrUpDateCross(6)
ScrMess(424, 0, "", "通信機の着信だ。")
ScrWaitKey()
ScrWinClear()
ScrBgmStop(1)
ScrWinType(1)
ScrWinFontSize(10, 10)
ScrMess(425, 0, "", "　　　　『穂村有里、死亡』")
ScrWaitKey()
ScrWinClear()
ScrWinType(0)
ScrWinFontSize(6, 6)
ScrMess(426, 21442, "修史", "「！？」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrBgmPlay(28769, 1)
ScrMess(427, 0, "", "なっ！")
ScrWaitKey()
ScrWinClear()
ScrMess(428, 0, "", "なん……で……有里が？")
ScrWaitKey()
ScrWinClear()
ScrMess(429, 0, "", "嘘だろ……？")
ScrWaitKey()
ScrWinClear()
ScrMess(430, 0, "", "何度も通信の文字を読む。")
ScrWaitKey()
ScrWinClear()
ScrMess(431, 0, "", "繰り返し。")
ScrWaitKey()
ScrWinClear()
ScrMess(432, 0, "", "何度も、何度も、何度も！")
ScrWaitKey()
ScrWinClear()
ScrMess(433, 0, "", "何度見ても消えない字に、俺は課長に連絡を取った。")
ScrWaitKey()
ScrWinClear()
ScrMess(434, 0, "", "笑って、何の冗談ですかと聞いた。")
ScrWaitKey()
ScrWinClear()
ScrMess(435, 0, "", "否定して欲しかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(436, 0, "", "返って来た返事は、冷酷だった。")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrChrDel(4)
ScrChrSet(5, 27610)
ScrJumpR(0x0002)
ScrWinFrame(1)
ScrMess(437, 0, "", "昨夜未明、穂村有里の死体を学院のガードが発見。")
ScrWaitKey()
ScrWinClear()
ScrMess(438, 0, "", "有里の所属する探偵社に引き取られ、<cr>エージェントの死亡は隠蔽されたと。")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrChrSet(5, 27272)
ScrJumpR(0x0002)
ScrWinFrame(1)
ScrWinFontSize(10, 10)
ScrMess(439, 21443, "修史", "「有里っ！！」")
ScrWaitKey()
ScrWinClear()
ScrMess(440, 21444, "修史", "「嘘だろ、有里！！！」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrMess(441, 0, "", "闇を切り裂くような声で、吼えた。")
ScrWaitKey()
ScrWinClear()
ScrMess(442, 0, "", "あのとき俺が手を離さなければ、<cr>キミは無事でいられたのか？")
ScrWaitKey()
ScrWinClear()
ScrMess(443, 0, "", "好きだと言えば良かったのか？")
ScrWaitKey()
ScrWinClear()
ScrMess(444, 0, "", "これは恋だと認めていれば、<cr>死なずにすんだのか！？")
ScrWaitKey()
ScrWinClear()
ScrMess(445, 0, "", "有里は無事で、一緒に朝を迎えていたのか？")
ScrWaitKey()
ScrWinClear()
ScrMess(446, 0, "", "認めるよ。<cr>認めるから、有里。")
ScrWaitKey()
ScrWinClear()
ScrMess(447, 0, "", "君が好きだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(448, 0, "", "君に恋をしている。")
ScrWaitKey()
ScrWinClear()
ScrMess(449, 0, "", "君が大切なんだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(450, 0, "", "すごくすごくすごく！")
ScrWaitKey()
ScrWinClear()
ScrMess(451, 21445, "修史", "「有里……有里……」")
ScrWaitKey()
ScrWinClear()
ScrMess(452, 0, "", "キミの長い髪。")
ScrWaitKey()
ScrWinClear()
ScrMess(453, 0, "", "好奇心旺盛な瞳。")
ScrWaitKey()
ScrWinClear()
ScrMess(454, 0, "", "甘い唇。")
ScrWaitKey()
ScrWinClear()
ScrMess(455, 0, "", "どうしてだろう。")
ScrWaitKey()
ScrWinClear()
ScrMess(456, 0, "", "今、キミの顔が思い出せない。")
ScrWaitKey()
ScrWinClear()
ScrMess(457, 0, "", "キミに恋する気持ちは、本物なのに。")
ScrWaitKey()
ScrWinClear()
ScrSePlay(272, 0)
ScrMess(458, 0, "", "空気を抱きしめ、ベッドに崩れ落ちる。")
ScrWaitKey()
ScrWinClear()
ScrMess(459, 21446, "修史", "「キミを護ることを命令してくれ、有里」")
ScrWaitKey()
ScrWinClear()
ScrMess(460, 21447, "修史", "「タダ働きでもいいからさぁ」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(6, 6)
ScrMess(461, 21448, "修史", "「アイギスも捨てるからさぁ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(462, 21449, "修史", "「なぁ、有里っ」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrChrSet(5, 27326)
ScrUpDateCross(12)
ScrWinFontSize(10, 10)
ScrMess(463, 21450, "修史", "「ゆぅ……りぃっ―――！！」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrMess(464, 0, "", "悲痛な俺の叫びが響いた。")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinType(1)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 4)
ScrWaitTime(30)
ScrMessageSpeed(1)
ScrWinFontColor(0, 0, 0)
ScrWinFontSize(6, 6)
ScrMess(465, 0, "", "　　　結局、俺の初恋は実らず……")
ScrWaitKey()
ScrWinClear()
ScrMess(466, 0, "", "永遠に、有里を失ってしまったのだった――")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrWinFontColor(128, 128, 128)
ScrMessageSpeed(0)
ScrChrSet(5, 27611)
ScrUpDateImage(120, 4)
ScrWaitTime(48)
ScrChrSet(5, 27612)
ScrUpDateCross(120)
ScrWaitTime(90)
ScrJump(0x002C)
