ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinFrameType(1)
ScrBgmStop(180)
ScrChrDel(0)
ScrChrSet(5, 28384)
ScrUpDateImage(90, 13)
ScrWaitTime(90)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 13)
ScrChrSet(5, 27261)
ScrJumpR(0x0002)
ScrBgmPlay(28770, 1)
ScrWaitIcon(1)
ScrWinFrame(1)
ScrMess(532, 0, "", "りおが忽然と姿を消してから、数日が経っていた。")
ScrWaitKey()
ScrWinClear()
ScrMess(533, 0, "", "アイギスに連絡を入れたが、彼女は帰っていない。")
ScrWaitKey()
ScrWinClear()
ScrMess(534, 0, "", "学院の敷地内をくまなく捜したが、<cr>りおの姿はどこにもなかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(535, 0, "", "それでも、見落としがあるかもしれないと、<cr>何度も同じ場所を捜して回る。")
ScrWaitKey()
ScrWinClear()
ScrMess(536, 0, "", "しかし、結果は一緒だ。")
ScrWaitKey()
ScrWinClear()
ScrMess(537, 0, "", "心配で、ほとんど眠れない日が続いている。")
ScrWaitKey()
ScrWinClear()
ScrMess(538, 0, "", "こんなときに雪乃たちが襲われたら……")
ScrWaitKey()
ScrWinClear()
ScrMess(539, 0, "", "そう思うと、ぞっとする。")
ScrWaitKey()
ScrWinClear()
ScrMess(540, 0, "", "しかし、俺にとっては、今は撫子会よりも、<cr>任務よりも、なによりも、大事なことだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(541, 0, "", "今朝からは、人が入りそうにない狭い場所を<cr>重点的に捜している。")
ScrWaitKey()
ScrWinClear()
ScrMess(542, 0, "", "例えば……<cr>プールの排水口とか……")
ScrWaitKey()
ScrWinClear()
ScrMess(543, 0, "", "いないと信じていても、捜してしまった。")
ScrWaitKey()
ScrWinClear()
ScrMess(544, 0, "", "もしかしたら、今もどこかで隠れていて、<cr>俺を待っているのかもしれない。")
ScrWaitKey()
ScrWinClear()
ScrMess(545, 0, "", "いや、きっとそうに決まってる。")
ScrWaitKey()
ScrWinClear()
ScrMess(546, 0, "", "そうだよな？")
ScrWaitKey()
ScrWinClear()
ScrMess(547, 0, "", "生きてるよな？　りお……")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrChrSet(5, 27277)
ScrJumpR(0x0002)
ScrWinFrame(1)
ScrMess(548, 23913, "修史", "「どこ行ったんだよ……りお」")
ScrWaitKey()
ScrWinClear()
ScrMess(549, 0, "", "シスター・リディアは、あれから姿を見せていない。")
ScrWaitKey()
ScrWinClear()
ScrMess(550, 0, "", "理由は体調不良らしいが、嘘だろう。")
ScrWaitKey()
ScrWinClear()
ScrSePlay(279, 0)
ScrWaitTime(30)
ScrMess(551, 23914, "修史", "「……っ！」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(280, 0)
ScrMess(552, 0, "", "突然鳴った通信機。<cr>俺は、すぐに通信ボタンを押した。")
ScrWaitKey()
ScrWinClear()
ScrWinFrameType(0)
ScrWinFontSize(6, 6)
ScrMess(553, 23915, "修史", "「りおかっ！？」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrBgmStop(1)
ScrChrSet(4, 28215)
ScrChrSet(0, 28248)
ScrUpDateCross(6)
ScrMess(554, 25544, "課長", "『私だ』")
ScrWaitKey()
ScrWinClear()
ScrMess(555, 0, "", "課長の真剣な顔つきを見て、嫌な予感がした。")
ScrWaitKey()
ScrWinClear()
ScrChrSet(0, 28247)
ScrUpDateCross(6)
ScrMess(556, 25545, "課長", "『中西りおが遺体で見つかった』")
ScrWaitKey()
ScrWinClear()
ScrMess(557, 23916, "修史", "「――え……」")
ScrWaitKey()
ScrWinClear()
ScrBgmPlay(28769, 1)
ScrChrSet(0, 28248)
ScrUpDateCross(6)
ScrMess(558, 25546, "課長", "『今朝、東京湾で発見された』")
ScrWaitKey()
ScrWinClear()
ScrMess(559, 0, "", "事務的な口調で、告げられた言葉は、<cr>最悪の内容で……")
ScrWaitKey()
ScrWinClear()
ScrMess(560, 23917, "修史", "「うそ、だ……うそだ！　<cr>　うそに決まってる！」")
ScrWaitKey()
ScrWinClear()
ScrChrDel(4)
ScrChrDel(0)
ScrUpDateCross(6)
ScrMess(561, 0, "", "懸命に否定する。")
ScrWaitKey()
ScrWinClear()
ScrMess(562, 0, "", "だが、悪辣に冗談ではあり得ないことは、<cr>その事務的な口調ゆえに、気づかざるを得ない。")
ScrWaitKey()
ScrWinClear()
ScrMess(563, 0, "", "俺は階段を下り、<cr>学院を出て、現場に向かった。")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrChrSet(5, 27326)
ScrJumpR(0x0002)
ScrChrSet(5, 27616)
ScrJumpR(0x0002)
ScrWinFrame(1)
ScrMess(564, 0, "", "ブルーのシートに覆われた場所に、りおがいた。")
ScrWaitKey()
ScrWinClear()
ScrMess(565, 0, "", "彼女は寒そうなくらい濡れていて……")
ScrWaitKey()
ScrWinClear()
ScrMess(566, 0, "", "顔は真っ白で……")
ScrWaitKey()
ScrWinClear()
ScrMess(567, 0, "", "あの日キスをした唇には、色がなかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(568, 0, "", "次から次に、涙が溢れてくる。")
ScrWaitKey()
ScrWinClear()
ScrMess(569, 23918, "修史", "「ごめん……りお……」")
ScrWaitKey()
ScrWinClear()
ScrMess(570, 0, "", "彼女を捜してボロボロになった俺の体が、<cr>彼女の体に崩れ落ちる。")
ScrWaitKey()
ScrWinClear()
ScrMess(571, 0, "", "あんな笑顔が最後だったなんて。")
ScrWaitKey()
ScrWinClear()
ScrMess(572, 0, "", "りおを護ってやるなんて、<cr>新人エージェントのくせに<cr>調子のいいこと言って……")
ScrWaitKey()
ScrWinClear()
ScrMess(573, 23919, "修史", "「りお、りお……りおぉぉっ！！」")
ScrWaitKey()
ScrWinClear()
ScrMess(574, 0, "", "俺のせいで……")
ScrWaitKey()
ScrWinClear()
ScrMess(575, 0, "", "俺のせいで……！！")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinType(1)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 4)
ScrWaitTime(30)
ScrMessageSpeed(1)
ScrWinFontColor(0, 0, 0)
ScrWinFontSize(6, 6)
ScrMess(576, 0, "", "　結局、一番大事な女の子を護ることが、<cr>　　　　　　出来なかった。")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrWinFontColor(128, 128, 128)
ScrMessageSpeed(0)
ScrChrSet(5, 27617)
ScrUpDateImage(120, 4)
ScrWaitTime(48)
ScrChrSet(5, 27618)
ScrUpDateCross(120)
ScrWaitTime(90)
ScrJump(0x0032)
