ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinFrameType(1)
ScrBgmStop(240)
ScrChrSet(5, 28523)
ScrUpDateImage(120, 4)
ScrWaitTime(120)
ScrWinType(1)
ScrMessageSpeed(1)
ScrWinFontColor(0, 0, 0)
ScrWinFontSize(6, 6)
ScrMess(670, 0, "", "　　　　そして、月日が流れて――")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrWinFontColor(128, 128, 128)
ScrWaitTime(60)
ScrMessageSpeed(0)
ScrWinType(0)
ScrChrSet(5, 27261)
ScrUpDateImage(120, 15)
ScrBgmPlay(28776, 1)
ScrWaitIcon(1)
ScrWinFrame(1)
ScrMess(671, 0, "", "雪乃たちの警護の任務を無事に終えた俺は、<cr>そのままテレジア学院にガードとして残り、<cr>蓮と共に卒業した。")
ScrWaitKey()
ScrWinClear()
ScrMess(672, 0, "", "雪乃は相続した遺産である財閥の運営のために、<cr>アメリカに渡り経済を学んでいる。")
ScrWaitKey()
ScrWinClear()
ScrMess(673, 0, "", "鞠奈は祖母の跡を継いで、<cr>テレジア学院の理事長に就任していた。")
ScrWaitKey()
ScrWinClear()
ScrMess(674, 0, "", "みんな自分の道を見つけて、それぞれ進んでいる。")
ScrWaitKey()
ScrWinClear()
ScrMess(675, 0, "", "そして、俺と蓮も……")
ScrWaitKey()
ScrWinClear()
ScrSePlay(127, 0)
ScrWinFontSize(4, 4)
ScrMess(676, 4969, "蓮", "「急げ、シュージ！<cr>　約束の時間に間に合わないぞ！」")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrMess(677, 0, "", "凛々しいスーツ姿の蓮が、<cr>足早に街を駆け抜けてゆく。")
ScrWaitKey()
ScrWinClear()
ScrMess(678, 0, "", "そんな蓮の後ろ姿を、道行く男達が<cr>眩しそうに振り返る。")
ScrWaitKey()
ScrWinClear()
ScrMess(679, 20794, "修史", "「こら、急に走るな！<cr>　打ち合わせにはまだ充分間に合うから……」")
ScrWaitKey()
ScrWinClear()
ScrMess(680, 20795, "修史", "「それよりも、下手に急いで車にぶつかったら<cr>　どうするんだよっ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(681, 4970, "蓮", "「そうか。それは気づかなかった……<cr>　充分気を付けることにするよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(682, 20796, "修史", "「それに、今回はヤバイ案件が絡んでるんだ。<cr>　また命を狙われることだってあるんだから」")
ScrWaitKey()
ScrWinClear()
ScrMess(683, 0, "", "ヒヤヒヤしつつ、警戒するように周囲を見回す。")
ScrWaitKey()
ScrWinClear()
ScrMess(684, 0, "", "何しろ、現在蓮が手がけている仕事は、<cr>危険が伴うのだ。")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinType(1)
ScrSeStop(1)
ScrBgmStop(120)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 4)
ScrWaitTime(30)
ScrMessageSpeed(1)
ScrWinFontColor(0, 0, 0)
ScrWinFontSize(6, 6)
ScrMess(685, 4971, "", "　　　　　　ダイジョーブ！<cr>　その時は臨時秘書兼、ボディ―ガードに<cr>　　　しっかり守ってもらうから！")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrWinFontColor(128, 128, 128)
ScrMessageSpeed(0)
ScrWaitTime(30)
ScrBgmPlay(28777, 1)
ScrChrSet(5, 27828)
ScrUpDateImage(90, 15)
ScrWinType(0)
ScrWaitIcon(1)
ScrWinFrame(1)
ScrMess(686, 0, "", "分厚い書類を抱えた弁護士が、<cr>こっちを振り向いてにっこり笑う。")
ScrWaitKey()
ScrWinClear()
ScrMess(687, 20797, "修史", "「……まったく」")
ScrWaitKey()
ScrWinClear()
ScrMess(688, 0, "", "この笑顔には負けるな。")
ScrWaitKey()
ScrWinClear()
ScrMess(689, 0, "", "……そう、俺はその後もアイギスの仕事を<cr>続けていた。")
ScrWaitKey()
ScrWinClear()
ScrMess(690, 0, "", "正義感の強い蓮がヤバい仕事を受けた時は、<cr>こうして彼女の臨時秘書をやっていたりする。")
ScrWaitKey()
ScrWinClear()
ScrMess(691, 20798, "修史", "「改めて言うけど……<cr>　今抱えてる弁護は、相当危険な案件なんだぞ、<cr>　もっと注意して動けよな」")
ScrWaitKey()
ScrWinClear()
ScrChrSet(5, 27829)
ScrUpDateCross(18)
ScrMess(692, 4972, "蓮", "「わかってる。<cr>　でも、シュージが護ってくれてれば、<cr>　あたしはいつでも大丈夫だよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(693, 0, "", "並んで歩き始めた蓮が、そっと腕を絡めてきた。")
ScrWaitKey()
ScrWinClear()
ScrMess(694, 20799, "修史", "「おいおい、俺をそんなに信用するなよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(695, 4973, "蓮", "「うん……<cr>　でも、シュージと一緒だからこそ、<cr>　あたしは今の仕事が続けられるんだ」")
ScrWaitKey()
ScrWinClear()
ScrMess(696, 0, "", "俺が護ることで、蓮は自分の正義を貫ける。")
ScrWaitKey()
ScrWinClear()
ScrMess(697, 0, "", "蓮にとっても、俺にとっても。<cr>それは幸せなことだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(698, 4974, "蓮", "「えへへっ♪<cr>　そういえば、今回のガードは女装じゃないんだ。<cr>　久しぶりにタエの姿を見たかったのに」")
ScrWaitKey()
ScrWinClear()
ScrMess(699, 20800, "修史", "「うー……もう俺は妙子じゃないんだからさ。<cr>　それに、本来はこの格好の方が落ち着くの！」")
ScrWaitKey()
ScrWinClear()
ScrMess(700, 0, "", "スーツ姿の自分を見てひと息つく。")
ScrWaitKey()
ScrWinClear()
ScrMess(701, 0, "", "女性弁護士の秘書役ということで、<cr>ガードに付くにあたり女装案が提示されたが。")
ScrWaitKey()
ScrWinClear()
ScrMess(702, 0, "", "なんとかそれは回避することができた。")
ScrWaitKey()
ScrWinClear()
ScrMess(703, 4975, "蓮", "「最近、シュージは女装してなかったものな。<cr>　そっちの仕事は、ユウに取られてしまったから」")
ScrWaitKey()
ScrWinClear()
ScrMess(704, 0, "", "取られたって言い方はどうだろう。")
ScrWaitKey()
ScrWinClear()
ScrMess(705, 0, "", "俺は別に女装をしたいわけじゃないんだぞ。")
ScrWaitKey()
ScrWinClear()
ScrMess(706, 20801, "修史", "「ああ、今日もあいつは女装して、<cr>　どっかのパーティに潜入してるだろうよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(707, 0, "", "すっかりアイギスに溶け込んだ優こと劉小燕は、<cr>見事な女性役をこなすエージェントになっていた。")
ScrWaitKey()
ScrWinClear()
ScrMess(708, 0, "", "本人も暗殺者から足を洗えたし、組織の貴重な女装役<cr>としても重宝されているので幸せそうだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(709, 0, "", "俺としても良かったと思う。")
ScrWaitKey()
ScrWinClear()
ScrMess(710, 4976, "蓮", "「女装して、パーティかぁ……<cr>　それは楽しそうだ」")
ScrWaitKey()
ScrWinClear()
ScrMess(711, 20802, "修史", "「優にとってはな」")
ScrWaitKey()
ScrWinClear()
ScrMess(712, 4977, "蓮", "「あはは。<cr>　シュージだと嫌がりそうだものな」")
ScrWaitKey()
ScrWinClear()
ScrMess(713, 20803, "修史", "「あたりまえだっての！」")
ScrWaitKey()
ScrWinClear()
ScrMess(714, 0, "", "懐かしい、テレジア学院での日々。")
ScrWaitKey()
ScrWinClear()
ScrMess(715, 0, "", "そして、仲間達。")
ScrWaitKey()
ScrWinClear()
ScrMess(716, 0, "", "あの頃は任務として過ごしていたけれど。")
ScrWaitKey()
ScrWinClear()
ScrMess(717, 0, "", "思い出すと胸が少し熱くなる。")
ScrWaitKey()
ScrWinClear()
ScrChrSet(5, 27830)
ScrUpDateCross(18)
ScrMess(718, 4978, "蓮", "「そういえば……この前マリが、<cr>　顔を見せに来てくれって言ってたぞ」")
ScrWaitKey()
ScrWinClear()
ScrMess(719, 20804, "修史", "「えっ、鞠奈さん……新理事長が？」")
ScrWaitKey()
ScrWinClear()
ScrMess(720, 4979, "蓮", "「うん。雪乃さまが久しぶりに<cr>　帰国されるっていうんで、それも兼ねてね」")
ScrWaitKey()
ScrWinClear()
ScrMess(721, 4980, "蓮", "「その時は、『妙子さまも連れて来て！』<cr>　と言われているんだが……」")
ScrWaitKey()
ScrWinClear()
ScrMess(722, 0, "", "妙子として学院を卒業したので、ふたりは俺の正体<cr>を知らないまま別れたのだ。")
ScrWaitKey()
ScrWinClear()
ScrChrSet(5, 27831)
ScrUpDateCross(18)
ScrMess(723, 4981, "蓮", "「なあ、マリ達にあたしが結婚したって<cr>　言ったらどんな反応するだろう？」")
ScrWaitKey()
ScrWinClear()
ScrMess(724, 0, "", "俺の顔を覗き込みながら、イタズラっぽく微笑む蓮。")
ScrWaitKey()
ScrWinClear()
ScrMess(725, 0, "", "蓮の左手には、薬指にキラリと指輪が光っている。")
ScrWaitKey()
ScrWinClear()
ScrMess(726, 0, "", "そう。")
ScrWaitKey()
ScrWinClear()
ScrMess(727, 0, "", "俺と蓮は結婚していたのだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(728, 20805, "修史", "「なっ！？<cr>　お、俺と結婚したって言うつもりなのか！？」")
ScrWaitKey()
ScrWinClear()
ScrMess(729, 4982, "蓮", "「それはそうだ、このまま秘密にしとくなんて<cr>　できないだろう？」")
ScrWaitKey()
ScrWinClear()
ScrMess(730, 0, "", "隠し事が出来ない、真っ直ぐな蓮だから。")
ScrWaitKey()
ScrWinClear()
ScrMess(731, 0, "", "大切な仲間であるふたりには、<cr>隠しておきたくないのだろう。")
ScrWaitKey()
ScrWinClear()
ScrMess(732, 0, "", "その気持ちはよくわかる。")
ScrWaitKey()
ScrWinClear()
ScrMess(733, 20806, "修史", "「うぅ……分かった。くれぐれも如月修史と、<cr>　山田妙子は別人ってことにしといてくれよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(734, 4983, "蓮", "「了解しました、旦那様♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(735, 0, "", "おどけたように言う蓮に、俺は頬を膨らませた。")
ScrWaitKey()
ScrWinClear()
ScrMess(736, 4984, "蓮", "「そんな可愛い顔をするな」")
ScrWaitKey()
ScrWinClear()
ScrMess(737, 20807, "修史", "「うるせ」")
ScrWaitKey()
ScrWinClear()
ScrMess(738, 0, "", "愛する妻にからかわれて、自然と顔が熱くなる。")
ScrWaitKey()
ScrWinClear()
ScrMess(739, 4985, "蓮", "「まあいい。今晩は３日かけて作ったボルシチを<cr>　出すからな。シュージの機嫌もすぐ直るだろう」")
ScrWaitKey()
ScrWinClear()
ScrMess(740, 20808, "修史", "「はは……それは楽しみだ」")
ScrWaitKey()
ScrWinClear()
ScrMess(741, 0, "", "俺は背中が寒くなるのを感じつつ、<cr>内心ホッとしていた。")
ScrWaitKey()
ScrWinClear()
ScrMess(742, 0, "", "……良かった、昨日内緒で手を加えておいて。")
ScrWaitKey()
ScrWinClear()
ScrMess(743, 0, "", "蓮との新婚生活はとても素晴らしい物だけれど。")
ScrWaitKey()
ScrWinClear()
ScrMess(744, 0, "", "相変わらず、蓮の料理の腕は凄まじかった。")
ScrWaitKey()
ScrWinClear()
ScrMess(745, 0, "", "シンプルな料理なら、そこそこ作れるようになった<cr>けれど。")
ScrWaitKey()
ScrWinClear()
ScrMess(746, 0, "", "蓮が手の込んだ料理をする時には、隙を見ては<cr>俺が修正を加えているのだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(747, 0, "", "それでも、やっぱり俺が一人で作った時よりも<cr>美味く感じるのは……")
ScrWaitKey()
ScrWinClear()
ScrMess(748, 0, "", "蓮の愛情のなせるワザなのかもしれない。")
ScrWaitKey()
ScrWinClear()
ScrMess(749, 0, "", "蓮は正義の弁護士であるのと同時に、<cr>俺の最愛の妻なのだから。")
ScrWaitKey()
ScrWinClear()
ScrChrSet(5, 27829)
ScrUpDateCross(18)
ScrMess(750, 4986, "蓮", "「おっと、もうすぐ約束の場所だ。<cr>　さっそく打ち合わせをしないとな……<cr>　ふふっ、腕がなるぞ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(751, 20809, "修史", "「ええ、頑張りましょう。<cr>　如月……いや、椿原弁護士！」")
ScrWaitKey()
ScrWinClear()
ScrWinFrame(0)
ScrWaitIcon(0)
ScrWinType(1)
ScrChrSet(5, 28523)
ScrUpDateImage(90, 4)
ScrWaitTime(30)
ScrMessageSpeed(1)
ScrWinFontColor(0, 0, 0)
ScrWinFontSize(6, 6)
ScrMess(752, 0, "", "　　俺たちは弁護士と秘書の顔に戻り、<cr>　　　　蓮の仕事場へと向かった。")
ScrWaitKey()
ScrWinClear()
ScrWinFontSize(0, 0)
ScrWinFontColor(128, 128, 128)
ScrMessageSpeed(0)
ScrChrSet(5, 27832)
ScrUpDateImage(120, 4)
ScrWaitTime(48)
ScrChrSet(5, 27833)
ScrUpDateCross(120)
ScrWaitTime(48)
ScrChrSet(5, 27834)
ScrUpDateCross(120)
ScrWaitTime(90)
ScrJump(0x0039)
