ScrIf(86, 0x0064, 3, 0, 0)
ScrIf(87, 0x0064, 2, 0, 0)
ScrWinFrame(0)
ScrWinFrameType(2)
ScrBgmStop(1)
ScrChrDel(0)
ScrChrSet(5, 28456)
ScrUpDateCross(12)
ScrWinFrame(1)
ScrMess(2474, 0, "", "本格的な護衛任務の始まりだが修史の心は暗い。<cr>乙女として振舞わなければならない上に、<cr>護衛対象に気を配らなくてはならないのだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(2475, 0, "", "放課後、歓迎会として撫子会で開かれたお茶会。<cr>そこで修史は、雪乃のお茶に睡眠薬が入っている<cr>ことを察知し、カップをわざと落として破壊する。")
ScrWaitKey()
ScrWinClear()
ScrMess(2476, 0, "", "雪乃を護ったはずの修史だが、それをドジだと<cr>責められてしまい、三人娘にいじられ遊ばれて<cr>しまうのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(2477, 0, "", "お茶会を終え帰ろうとすると雪乃の下駄箱から<cr>靴が盗まれ、代りに切り刻まれた雪乃の写真が<cr>入れられていた。悪質な悪戯に一同は憤慨する。")
ScrWaitKey()
ScrWinClear()
ScrMess(2478, 0, "", "しかしそれは、雪乃と修史にとって悪戯ではなく<cr>脅迫のように思えるのだった……")
ScrWaitKey()
ScrWinClear()
ScrSelect(2479, 3, 2, "共通ルート", "「女であること」", "このシーンをスキップしますか？", "『ＹＥＳ』", "『ＮＯ』")
ScrIf(88, 0x0063, 0, 0, 0)
ScrIf(89, 0x0064, 0, 0, 1)
