ScrMess(4781, 0, "", "笹塚先生に出された大量の宿題を<cr>やり遂げる為に徹夜する修史と蓮。")
ScrWaitKey()
ScrWinClear()
ScrMess(4782, 0, "", "そんな二人に差し入れを持って来たり、<cr>夜食を作ってくれたりと気を遣ってくれた<cr>有里に修史は感謝の意を伝えるのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(4783, 9435, "有里", "「あー。いーのいーの。気にしないで」")
ScrWaitKey()
ScrWinClear()
ScrMess(4784, 0, "", "そう答える有里に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(379, 1)
ScrJump(0x00A0)
