ScrMess(6580, 0, "", "笹塚が雪乃を襲った容疑者と考えた修史は、<cr>雪乃が受ける笹塚の授業を妨害する。")
ScrWaitKey()
ScrWinClear()
ScrMess(6581, 0, "", "授業を妨害した事への説教の為か、放課後<cr>職員室まで来るように笹塚に言われる修史。")
ScrWaitKey()
ScrWinClear()
ScrMess(6582, 0, "", "罠の可能性を考えた修史は、念の為に<cr>有里に全てを相談して、協力を得るか<cr>悩むのだった……")
ScrWaitKey()
ScrWinClear()
ScrMov(380, 1)
ScrJump(0x00C5)
