ScrMess(7895, 0, "", "りおのために寮のシェフを捜して料理を作って<cr>もらった修史。待っていると、りおは大浴場で<cr>お風呂に入ってから戻ってくる。")
ScrWaitKey()
ScrWinClear()
ScrMess(7896, 0, "", "それを聞いた修史は、自分は入れないのにと<cr>悔しさを募らせる。そんな修史の気持ちには<cr>気付かずに、りおは料理に喜ぶのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(7897, 14186, "りお", "「一応、お礼は言ってあげます。<cr>　ありがとーございました！」")
ScrWaitKey()
ScrWinClear()
ScrMess(7898, 0, "", "そんなりおに修史は……")
ScrWaitKey()
ScrWinClear()
ScrJump(0x00E6)
