ScrMess(7901, 0, "", "さっさと帰れと言いたいところだが、<cr>お、俺はこれでもオトナだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(7902, 0, "", "オトナはオトナの対応をしなければならない。")
ScrWaitKey()
ScrWinClear()
ScrMess(7903, 0, "", "りおは、この料理を食べて当然の働きを<cr>したんだし、この学院に登録をしているなら、<cr>風呂にはいることだって許される。")
ScrWaitKey()
ScrWinClear()
ScrMess(7904, 0, "", "なんらおかしいところはないのだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(7905, 0, "", "俺は喉から声を振り絞る。")
ScrWaitKey()
ScrWinClear()
ScrMess(7906, 16470, "修史", "「どう……いたしまして……」")
ScrWaitKey()
ScrWinClear()
ScrChrSet(0, 28365)
ScrUpDateCross(6)
ScrMess(7907, 14187, "りお", "「えへへぇ。いただきまーっす！」")
ScrWaitKey()
ScrWinClear()
ScrMess(7908, 0, "", "満面の笑みだな、おい。")
ScrWaitKey()
ScrWinClear()
ScrMess(7909, 0, "", "俺はお前が羨ましいぞ、中西りお！")
ScrWaitKey()
ScrWinClear()
ScrMov(36, 1)
ScrJump(0x00ED)
