ScrMess(17030, 0, "", "壇上から飛び降りた鞠奈は、<cr>修史たちのグループまでやってくる。")
ScrWaitKey()
ScrWinClear()
ScrMess(17031, 0, "", "そんな鞠奈を後ろから抱きしめた蓮は<cr>抱き心地が最高と言って、修史にも<cr>鞠奈を抱きしめるのを勧めるのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(17032, 6396, "鞠奈", "「やぁ～ん、そんなのされたくな～い」")
ScrWaitKey()
ScrWinClear()
ScrMess(17033, 0, "", "嫌がる鞠奈に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(401, 1)
ScrJump(0x0220)
