ScrMess(17682, 0, "", "蓮の父親への不正疑惑が映し出されている<cr>テレビを見る鞠奈と修史。蓮が可愛そう<cr>だと告げるも、鞠奈は素っ気無い態度だ。")
ScrWaitKey()
ScrWinClear()
ScrMess(17683, 0, "", "両親を失った鞠奈は、疑惑があっても親が<cr>いるだけ幸せだと言う。それを聞いても、<cr>修史は蓮が心配だと言うのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(17684, 0, "", "そして修史は鞠奈に理由を告げる……")
ScrWaitKey()
ScrWinClear()
ScrMov(407, 1)
ScrJump(0x0250)
