ScrMess(17817, 0, "", "蓮の挑発に乗って、修史を巻き込み寸劇を<cr>行う事になる鞠奈。")
ScrWaitKey()
ScrWinClear()
ScrMess(17818, 0, "", "それはドレスの仕立て屋に、もっと豪華に<cr>胸を大きく見せるようにしろと無理難題を<cr>注文するワガママ姫という内容だった。")
ScrWaitKey()
ScrWinClear()
ScrMess(17819, 6605, "鞠奈", "「言う通りにしなきゃ、即解雇っ」")
ScrWaitKey()
ScrWinClear()
ScrMess(17820, 0, "", "鞠奈姫の注文に仕立て屋役の修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(408, 1)
ScrJump(0x025C)
