ScrMess(19049, 0, "", "鞠奈の調査報告書によると、<cr>彼女は事故で両親を亡くしている。")
ScrWaitKey()
ScrWinClear()
ScrMess(19050, 0, "", "両親は幼い彼女を守るように、<cr>覆い被さって死んでいたらしい。")
ScrWaitKey()
ScrWinClear()
ScrMess(19051, 0, "", "相当、辛い経験だったはずだ。")
ScrWaitKey()
ScrWinClear()
ScrJump(0x02A7)
