ScrMess(23912, 0, "", "蓮は笑った。")
ScrWaitKey()
ScrWinClear()
ScrMess(23913, 0, "", "その顔を見て、俺も少し気が緩む。")
ScrWaitKey()
ScrWinClear()
ScrMess(23914, 0, "", "なにもしないのは、とても辛いことだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(23915, 0, "", "蓮には頑張って欲しい。")
ScrWaitKey()
ScrWinClear()
ScrMess(23916, 0, "", "心からそう思うよ。")
ScrWaitKey()
ScrWinClear()
ScrJump(0x035A)
