ScrMess(24309, 0, "", "牛丼を前にして眠ってしまっている蓮。<cr>起こしてもダメだったので、修史は自分の<cr>牛丼を食べて起きるのを待つ事にする。")
ScrWaitKey()
ScrWinClear()
ScrMess(24310, 0, "", "食べ終えた食器を洗い終えても起きない蓮に、<cr>修史は諦めて帰りたい旨を伝える。すると蓮は<cr>寝ぼけながらもダメと言うのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(24311, 5351, "蓮", "「もすこし……待って……」")
ScrWaitKey()
ScrWinClear()
ScrMess(24312, 0, "", "そんな蓮に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(429, 1)
ScrJump(0x0376)
