ScrMess(31407, 0, "", "食べすぎで倒れていたりおが目を覚ます。<cr>りおの身を心配していた修史がちょっと<cr>怒ると、りおは突然涙をこぼしはじめる。")
ScrWaitKey()
ScrWinClear()
ScrMess(31408, 0, "", "しばらくして泣きやんだりおは、修史に<cr>学園祭が楽しかった事を告げつつ迷惑を<cr>かけた事を素直に謝るのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(31409, 14648, "りお", "「本当に、ごめんなさい」")
ScrWaitKey()
ScrWinClear()
ScrMess(31410, 0, "", "そんなりおに修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(444, 1)
ScrJump(0x046C)
