ScrMess(34105, 0, "", "撫子会の演劇に出る事になった設子。<cr>しかし演劇の経験など無く、物語の<cr>内容もよく知らないのだと言う。")
ScrWaitKey()
ScrWinClear()
ScrMess(34106, 0, "", "人前に出る恥かしさも相まって、<cr>修史たちに自分が出てもいいのかと<cr>不安そうに弱音を吐くのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(34107, 8585, "設子", "「ですから、舞台に立っても上手く喋れるかどうか」")
ScrWaitKey()
ScrWinClear()
ScrMess(34108, 0, "", "不安そうな設子に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(450, 1)
ScrJump(0x04C2)
