ScrMess(34390, 0, "", "修史が自分がプレゼントしたブローチを<cr>着けている事に喜ぶ設子。そして学園の<cr>人気者と言われて照れる修史だった。")
ScrWaitKey()
ScrWinClear()
ScrMess(34391, 8652, "設子", "「学園でも人気者の妙子さまが、<cr>　わたくしなんかのプレゼントを<cr>　大切にしてくださって」")
ScrWaitKey()
ScrWinClear()
ScrMess(34392, 0, "", "設子にそう言われた修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(451, 1)
ScrJump(0x04CE)
