ScrMess(40978, 0, "", "指を切ってしまった修史を治療しながら<cr>雪乃はその身を心配するあまり、田舎に<cr>戻った方がいいのではと提案してしまう。")
ScrWaitKey()
ScrWinClear()
ScrMess(40979, 0, "", "その言葉に修史は田舎には戻らないと<cr>きっぱりと言う。その言葉に雪乃は、<cr>戻らない理由を尋ねるのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(40980, 1504, "雪乃", "「……なぜ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(40981, 0, "", "そんな雪乃に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(466, 1)
ScrJump(0x05B4)
