ScrMess(41500, 0, "", "手作りのお弁当を修史に自ら食べさせる<cr>雪乃。食べるペースを無視した供給は、<cr>修史の口の中をすぐに一杯にしてしまう。")
ScrWaitKey()
ScrWinClear()
ScrMess(41501, 0, "", "飲み込む時間もあたえず食べ物を<cr>口に入れようとする雪乃を修史は<cr>なんとか止めようとするのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(41502, 1660, "雪乃", "「さあ妙子、お口を開けて」")
ScrWaitKey()
ScrWinClear()
ScrMess(41503, 0, "", "口の中が一杯の修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(469, 1)
ScrJump(0x05D8)
