ScrMess(42292, 0, "", "雪乃に言われて翌日の学園祭準備の手伝いを<cr>する事になった修史。雪乃の部屋に行くと、<cr>そこは書類で散らかっている有様だった。")
ScrWaitKey()
ScrWinClear()
ScrMess(42293, 0, "", "学園祭前日にも拘わらず書類処理に追われる<cr>雪乃の姿に、修史はなんでもっと早くから<cr>頼ってくれなかったのかと訊ねるのだった。")
ScrWaitKey()
ScrWinClear()
ScrMess(42294, 2818, "雪乃", "「あ、あなたを頼らなかったのは、<cr>　頼りにならないとか、<cr>　そういうコトじゃないのよ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(42295, 0, "", "そんな雪乃に修史は……")
ScrWaitKey()
ScrWinClear()
ScrMov(473, 1)
ScrJump(0x0608)
