ScrWinFrame(1)
ScrMess(624, 11463, "彰", "「晶子、いい加減にしろ！　ハッキリ言うけど、今日の<cr>晶子じゃオレに勝てないよ」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30295, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(625, 828, "晶子", "「でも、それはやってみないと――」")
ScrWaitKey()
ScrWinClear()
ScrMess(626, 11464, "彰", "「やらなくてもわかる。自分が冷静じゃないってわから<cr>ないのか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(627, 11465, "彰", "「あんまりしつこいと今日のデートはこれで終わりにす<cr>るぞ？　お詫びならもう、十分済ませてるはずだから<cr>な」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30271, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(628, 829, "晶子", "「え……そんなっ」")
ScrWaitKey()
ScrWinClear()
ScrMess(629, 0, "", "少し強めの口調で叱ると、晶子はビクンと体を震わせ、<cr>寂しそうに俯いた。")
ScrWaitKey()
ScrWinClear()
ScrMess(630, 0, "", "しまった。ちょっと言いすぎたかな？")
ScrWaitKey()
ScrWinClear()
ScrMess(631, 0, "", "でも今の晶子を冷静にさせるには、このぐらいは必要な<cr>はずだ。")
ScrWaitKey()
ScrWinClear()
ScrMess(632, 0, "", "きっと晶子もわかってくれるよな？")
ScrWaitKey()
ScrWinClear()
ScrMess(633, 830, "晶子", "「ごめんなさい、兄さん。確かに私、冷静じゃなかった<cr>です」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30295, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(634, 831, "晶子", "「だから……もう少しだけ私に付き合ってください。晩<cr>御飯、兄さんと一緒にラーメンが食べたいです」")
ScrWaitKey()
ScrWinClear()
ScrMess(635, 11466, "彰", "「ほっ。そうか、分かってくれたらいいんだ」")
ScrWaitKey()
ScrWinClear()
ScrMess(636, 11467, "彰", "「さっきはキツイこと言っちゃってごめんな。オレも晶<cr>子と一緒に晩御飯を食べたいよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(637, 11468, "彰", "「さ。それじゃあどこのお店で食べようか？　出来れば<cr>この近くにしたいな」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24310, 0)
ScrMess(638, 0, "", "オレは沈んでしまった空気を吹き飛ばすように、大げさ<cr>にラーメンマップを広げた。")
ScrWaitKey()
ScrWinClear()
ScrMess(639, 0, "", "そして近くのお店を何点か指差しながら晶子に話かけ<cr>る。")
ScrWaitKey()
ScrWinClear()
ScrMess(640, 11469, "彰", "「味噌、醤油、豚骨……この近くだけでも色んなお店が<cr>あるけど、晶子は確か醤油ラーメンが好きだったよな」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30261, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(641, 832, "晶子", "「え？」")
ScrWaitKey()
ScrWinClear()
ScrMess(642, 11470, "彰", "「だったらこの店なんかどうだ？　醤油しか置いてない<cr>けど、こだわりの専門店なんだって」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30285, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(643, 833, "晶子", "「あ、あの、ちょっと待ってください」")
ScrWaitKey()
ScrWinClear()
ScrMess(644, 11471, "彰", "「ん？　どうした？」")
ScrWaitKey()
ScrWinClear()
ScrMess(645, 834, "晶子", "「私は別に醤油味が好きってわけじゃないんですけど、<cr>その情報どこで手に入れたんですか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(646, 11472, "彰", "「え？　う、嘘だ。晶子は醤油好きのはずだろ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(647, 11473, "彰", "「だって子供のころ、いつも退院した後は母さんに醤油<cr>ラーメン作ってもらってたじゃないか」")
ScrWaitKey()
ScrWinClear()
ScrMess(648, 11474, "彰", "「あれは醤油が一番好きだってことだろ？　父さんが<cr>作った味噌ラーメンには、手もつけなかった記憶がある<cr>ぞ？」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30251, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(649, 835, "晶子", "「ああ、あれは味の問題じゃなくて、単に醤油以外は食<cr>べちゃダメだって、お医者様に止められてたんです」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30253, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(650, 836, "晶子", "「当時はほら、まだ食事制限があったから。お菓子だっ<cr>てあんまり食べれませんでしたよね？」")
ScrWaitKey()
ScrWinClear()
ScrMess(651, 11475, "彰", "「そうか、そういえばそうだったな……」")
ScrWaitKey()
ScrWinClear()
ScrMess(652, 0, "", "思い出したぞ。")
ScrWaitKey()
ScrWinClear()
ScrMess(653, 0, "", "昔はよく晶子だけお菓子が食べられなかったから、病院<cr>でも一人寂しそうにしてた気がする。")
ScrWaitKey()
ScrWinClear()
ScrMess(654, 0, "", "だからオレもお菓子なんか食べないって言ったら、晶子<cr>は兄さんが我慢するのはもっと嫌だって泣き出しちゃっ<cr>たんだっけ。")
ScrWaitKey()
ScrWinClear()
ScrMess(655, 0, "", "辛いのは晶子の方なのに、それでもオレのことを想って<cr>くれるなんて……")
ScrWaitKey()
ScrWinClear()
ScrMess(656, 11476, "彰", "「はぁ……あの頃の晶子は本当に可愛かったなぁ」")
ScrWaitKey()
ScrWinClear()
ScrMess(657, 0, "", "いや、もちろん今も今で別の可愛さがあるんだけどね。")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30251, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(658, 837, "晶子", "「食事制限がなくなったのは、ルピナスに入ってからで<cr>すよ」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30253, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(659, 838, "晶子", "「けどルピナスに入ってからは、ラーメンみたいなもの<cr>は食べられなかったですね。だからラーメンは本当に久<cr>しぶりです」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30287, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(660, 839, "晶子", "「そうだ！　今日はせっかくだから、醤油以外の味を食<cr>べてみたいです」")
ScrWaitKey()
ScrWinClear()
ScrMess(661, 840, "晶子", "「豚骨ってスープが白いんですよね？　あれはどうやっ<cr>て白くしてるんですか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(662, 11477, "彰", "「ああ、それは豚の骨を煮込んで……って、オレも詳し<cr>く知らないや」")
ScrWaitKey()
ScrWinClear()
ScrMess(663, 11478, "彰", "「でもお店の人なら知ってるはずだから、今日は豚骨の<cr>お店にしてみるか？」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30253, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(664, 841, "晶子", "「はい♪　白いスープ、楽しみです」")
ScrWaitKey()
ScrWinClear()
ScrLbg(28880, 0)
ScrDrawEx(0, 0, 90, 1)
ScrMess(665, 0, "", "こうしてオレと晶子は、裏路地にある豚骨ラーメンがオ<cr>ススメだという店へ向かうことになった。")
ScrWaitKey()
ScrWinClear()
ScrMess(666, 0, "", "前もって場所を調べていたおかげで、店の前まで迷うこ<cr>となく到着する。")
ScrWaitKey()
ScrWinClear()
ScrBgmStop(150)
ScrMess(667, 0, "", "さっそく店内に入ると、やはり人が多い時間帯のせい<cr>か、テーブル席はなく、オレ達はカウンターに座ること<cr>になった。")
ScrWaitKey()
ScrWinClear()
ScrLbg(29270, 0)
ScrDrawEx(10, 0, 90, 1)
ScrBgmPlay(30648, 1)
ScrWaitTime(30)
ScrMess(668, 17794, "店長", "「へい、お待ち」")
ScrWaitKey()
ScrWinClear()
ScrMess(669, 842, "晶子", "「わあ～っ！　これが豚骨ですか？　ホントにスープが<cr>白くて、いい匂いがしておいしそーっ♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(670, 0, "", "注文していた豚骨ラーメンが届き、感嘆の声を漏らす。")
ScrWaitKey()
ScrWinClear()
ScrMess(671, 0, "", "ラーメンくらいで大げさだなあ……と思ったけど、確か<cr>にここのラーメンは盛り付けも綺麗でおいしそうだっ<cr>た。")
ScrWaitKey()
ScrWinClear()
ScrMess(672, 0, "", "このお店、評判以上にあたりかもしれないな。")
ScrWaitKey()
ScrWinClear()
ScrMess(673, 843, "晶子", "「あーん、兄さん。私、もう待てません。先に食べちゃ<cr>いますよ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(674, 11479, "彰", "「ダメダメ。いただきますを言わなきゃ。ほら、一緒に<cr>手を合わせて……」")
ScrWaitKey()
ScrWinClear()
ScrMess(675, 992, "月丘兄妹", "「いただきまーす♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(676, 844, "晶子", "「ずるずるずる。はむはむ……はむはむはむ……」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29271, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(677, 845, "晶子", "「うーんっ！　おいひーれふっ♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(678, 11480, "彰", "「ああ、こりゃうまい！」")
ScrWaitKey()
ScrWinClear()
ScrMess(679, 846, "晶子", "「ずるずる……濃厚なスープが麺に上手く絡まっ<cr>て……はふはふっ、豚骨ってこんなにおいしいんです<cr>か？」")
ScrWaitKey()
ScrWinClear()
ScrMess(680, 11481, "彰", "「いや、オレも豚骨ラーメンは色々食べてきたけど、こ<cr>こまで美味しいのは初めてだよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(681, 11482, "彰", "「この店に来て正解だったな。今まで食べてきたラーメ<cr>ンの中で、間違いなく一番だよ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(682, 17795, "店長", "「へへへ、そいつはありがとうお嬢さん。店長としてそ<cr>う言ってもらえると嬉しいよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(683, 17796, "店長", "「ところでお客さんは顔がそっくりだけど、双子か何か<cr>かい？」")
ScrWaitKey()
ScrWinClear()
ScrMess(684, 17797, "店長", "「何にしろ、女の子同士でご来店なんて珍しいから、内<cr>緒で麺の量サービスしといたよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(685, 11483, "彰", "「へ？　いや、オレは男なんですけど――」")
ScrWaitKey()
ScrWinClear()
ScrMess(686, 847, "晶子", "「わあっ！　ありがとうございます。よかったですね、<cr>姉さん♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(687, 11484, "彰", "「はあ？　ちょ、ちょっと晶子、誰が姉さんなんだ<cr>よ！？」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29272, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(688, 848, "晶子", "「しーっ。せっかくサービスしてもらったんですから、<cr>黙ってればいいじゃないですか」")
ScrWaitKey()
ScrWinClear()
ScrMess(689, 849, "晶子", "「人の好意を無下にするのはよくないって、兄さんもよ<cr>く言いますよね？」")
ScrWaitKey()
ScrWinClear()
ScrMess(690, 11485, "彰", "「ぐっ……わ、わかったよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(691, 0, "", "まあいい。どうせ間違えられるのは初めてじゃないし、<cr>そのたびに訂正するのも面倒だ。")
ScrWaitKey()
ScrWinClear()
ScrMess(692, 0, "", "しかし……男口調で男の恰好してるのに、どうして女の<cr>子に間違われるんだろう？")
ScrWaitKey()
ScrWinClear()
ScrMess(693, 0, "", "オレってそんなに男の子に見えないのかな？")
ScrWaitKey()
ScrWinClear()
ScrMess(694, 0, "", "見た目はともかく、性格的には結構男らしいって思って<cr>るんだけど……")
ScrWaitKey()
ScrWinClear()
ScrLbg(29271, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(695, 850, "晶子", "「あ、ところで店長さん、私聞きたいことがあるんです<cr>けど、豚骨ってどうして白いんですか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(696, 17798, "店長", "「ああ、そいつはアレだよ。豚の骨を煮込んでるとき<cr>に、骨髄から溶けたゼラチンがスープを白くしてるん<cr>だ」")
ScrWaitKey()
ScrWinClear()
ScrMess(697, 17799, "店長", "「ま、ウチはもうひとつ理由があって、他の店よりさら<cr>に白いんだけど……アレはまあ企業秘密だな～」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29272, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(698, 851, "晶子", "「えーっ、そこまで言っておいて企業秘密ですか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(699, 852, "晶子", "「私も自分で作ってみたいと思ったのに……店長さん、<cr>気を持たせるだけ持たせておいてずるいですよお」")
ScrWaitKey()
ScrWinClear()
ScrMess(700, 0, "", "そう言いながら晶子は、ぷっくりと頬を膨らませて、可<cr>愛くふてくされ顔を作った。")
ScrWaitKey()
ScrWinClear()
ScrMess(701, 0, "", "するとそれまで料理人の顔をしていた店長の表情が一<cr>変。")
ScrWaitKey()
ScrWinClear()
ScrMess(702, 0, "", "デレデレと顔を緩ませて、情けないほどに目じりを下げ<cr>てしまう。")
ScrWaitKey()
ScrWinClear()
ScrMess(703, 17800, "店長", "「いやぁ～、そう言われるとオジサンも困っちゃう<cr>なぁ」")
ScrWaitKey()
ScrWinClear()
ScrMess(704, 17801, "店長", "「教えたいけど、秘伝だしなぁ～」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29271, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(705, 853, "晶子", "「聞きたいです聞きたいです。お願いしますよ店長さー<cr>ん」")
ScrWaitKey()
ScrWinClear()
ScrMess(706, 17802, "店長", "「でへへへ……しょ、しょうがないなあ。じゃあお嬢<cr>ちゃんだけに特別だぞ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(707, 854, "晶子", "「わあっ、ありがとうございます♪」")
ScrWaitKey()
ScrWinClear()
ScrMess(708, 0, "", "晶子の可愛いおねだりに、終始デレデレしっぱなしだっ<cr>た店長は、あっさりと企業秘密を暴露した。")
ScrWaitKey()
ScrWinClear()
ScrMess(709, 0, "", "い、いいのか店長？")
ScrWaitKey()
ScrWinClear()
ScrMess(710, 0, "", "確かにさっきの晶子は抱きしめちゃいたいほど可愛かっ<cr>たけど、厨房の奥さんらしき人が凄い目で睨んでるぞ？")
ScrWaitKey()
ScrWinClear()
ScrMess(711, 0, "", "このお店……明日でつぶれたりしないだろうな？")
ScrWaitKey()
ScrWinClear()
ScrMess(712, 17803, "店長", "「で、そこに背油と牛乳、最後にチーズを入れるんだ」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29270, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(713, 855, "晶子", "「なるほどー。確かにそれは思い付きませんね」")
ScrWaitKey()
ScrWinClear()
ScrMess(714, 17804, "店長", "「だろう？　どうだい、興味があるなら今度作ってると<cr>こ見せてやろうか？　何ならアルバイトとして雇っても<cr>――」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29271, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(715, 856, "晶子", "「あ、それなら大丈夫です。今ので作り方覚えましたか<cr>ら。どうもありがとうございました。後は自分で作りま<cr>す」")
ScrWaitKey()
ScrWinClear()
ScrMess(716, 17805, "店長", "「そ、そうか。ならいいんだ……は、ははは……」")
ScrWaitKey()
ScrWinClear()
ScrMess(717, 0, "", "ガックリと肩を落とす店長と、対照的に満足げな晶子。")
ScrWaitKey()
ScrWinClear()
ScrMess(718, 0, "", "晶子のやつ、情報を貰うだけ貰って後は用済みと<cr>か……意識してないんだろうけどかなりの小悪魔ぶりだ<cr>な。")
ScrWaitKey()
ScrWinClear()
ScrMess(719, 0, "", "店長も邪な気持ちがあったんだろうけど、まるで妹に振<cr>り回される自分の姿を見ているみたいで思わず同情した<cr>くなる。")
ScrWaitKey()
ScrWinClear()
ScrMess(720, 11486, "彰", "「晶子って……結構ワルい女だよな」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29270, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(721, 857, "晶子", "「え？　なんですか急に？」")
ScrWaitKey()
ScrWinClear()
ScrMess(722, 11487, "彰", "「いや、自覚がないならいい。でもこんな調子だから犠<cr>牲者が増えていくんだろうな……」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29272, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(723, 858, "晶子", "「なんですかそれ？　人を悪魔みたいに言って」")
ScrWaitKey()
ScrWinClear()
ScrMess(724, 859, "晶子", "「せっかくここのラーメン兄さんに作ってあげようと<cr>思ったのに、文句言うなら食べさせてあげませんよー<cr>だ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(725, 17806, "店長", "「兄さんだって！？　その子が男ぉ！？」")
ScrWaitKey()
ScrWinClear()
ScrMess(726, 11488, "彰", "「お、おい晶子！」")
ScrWaitKey()
ScrWinClear()
ScrLbg(29270, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(727, 860, "晶子", "「あっ、しまった」")
ScrWaitKey()
ScrWinClear()
ScrMess(728, 17807, "店長", "「し……信じられん。お前、男だったのか……」")
ScrWaitKey()
ScrWinClear()
ScrMess(729, 11489, "彰", "「あ、あはははは、どうも……」")
ScrWaitKey()
ScrWinClear()
ScrMess(730, 0, "", "あまりの衝撃に、口を開けたまま硬直する店長。")
ScrWaitKey()
ScrWinClear()
ScrMess(731, 0, "", "も、もう苦笑いするしかないな。さっさと食べて店を出<cr>よう。")
ScrWaitKey()
ScrWinClear()
ScrLbg(28881, 0)
ScrDrawEx(0, 0, 90, 1)
ScrMess(732, 0, "", "この後、オレは急ピッチでラーメンを食べ終えると、ぐ<cr>ずる晶子を連れ出してお会計を済ませ、早々に店を出<cr>た。")
ScrWaitKey()
ScrWinClear()
ScrMess(733, 0, "", "店長さん……別れ際に奥さんに引っ張られて奥に引っ込<cr>んじゃったけど、色んな意味で大丈夫だろうか？")
ScrWaitKey()
ScrWinClear()
ScrMess(734, 0, "", "はぁ。ここのラーメン凄く美味しかったのに、晶子のせ<cr>いで二度と入れなくなってしまった。")
ScrWaitKey()
ScrWinClear()
ScrSeStop(0)
ScrBgmStop(120)
ScrLbg(28889, 0)
ScrDrawEx(0, 0, 120, 1)
ScrWaitTime(60)
ScrJump(0x010B)
