ScrLchr(1, 30259, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrWinFrame(1)
ScrMess(957, 938, "晶子", "「もう……しょうがないですねぇ」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30279, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(958, 939, "晶子", "「わかりました。それじゃあ私も一緒に入ってあげま<cr>す」")
ScrWaitKey()
ScrWinClear()
ScrMess(959, 11563, "彰", "「え……」")
ScrWaitKey()
ScrWinClear()
ScrMess(960, 0, "", "一緒に……入る？")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24308, 0)
ScrWinFrame(0)
ScrShake(2, 60)
ScrShake(2, 60)
ScrMess(961, 11564, "彰", "「え、ええええええっ！！？？」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30284, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(962, 940, "晶子", "「ちょ、ちょっと兄さん、声が大きいです。こんな時間<cr>に迷惑ですよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(963, 11565, "彰", "「え？　いや、でも一緒にって、オレと晶子が！？」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30254, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(964, 941, "晶子", "「何ですかそのくらいで驚いて。私がルピナスに入る前<cr>はいつも一緒に入ってたじゃないですか」")
ScrWaitKey()
ScrWinClear()
ScrMess(965, 11566, "彰", "「で、でもオレ達もう大人だし、晶子は恥ずかしくない<cr>のかよ？」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30260, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(966, 942, "晶子", "「私？　別に恥ずかしくないですよ」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30250, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(967, 943, "晶子", "「私と兄さんの違いなんてあるかないかくらいですし、<cr>兄妹なんだから一緒にお風呂くらい普通じゃないです<cr>か」")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30260, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(968, 944, "晶子", "「流石にこれがお父さんなら別ですけどね。まあルピナ<cr>スにはまだ一緒に入ってる子も多いみたいですけど」")
ScrWaitKey()
ScrWinClear()
ScrMess(969, 11567, "彰", "「なっ――！」")
ScrWaitKey()
ScrWinClear()
ScrMess(970, 0, "", "こ、この年で父親と一緒にお風呂だなんて……恐るべ<cr>し、お嬢様学園。")
ScrWaitKey()
ScrWinClear()
ScrLchr(1, 30252, 0, 0, 0)
ScrDrawEx(0, 0, 30, 0)
ScrMess(971, 945, "晶子", "「さ、行きましょう兄さん。着替えは私のネグリジェが<cr>ありますから、ちゃんと自分の分持ってきてください<cr>ね」")
ScrWaitKey()
ScrWinClear()
ScrMess(972, 11568, "彰", "「う、うん」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24389, 0)
ScrLchr(1, 0, 0, 0, 0)
ScrDrawEx(0, 0, 60, 1)
ScrMess(973, 0, "", "オレと晶子が……一緒にお風呂。")
ScrWaitKey()
ScrWinClear()
ScrMess(974, 0, "", "冷静に考えたら兄妹なんだから、裸を見ても何も問題な<cr>いんだろうけど……")
ScrWaitKey()
ScrWinClear()
ScrMess(975, 0, "", "い、色んな意味で我慢できるだろうか？")
ScrWaitKey()
ScrWinClear()
ScrBgmStop(120)
ScrLbg(28881, 0)
ScrDrawEx(0, 0, 120, 1)
ScrWaitTime(30)
ScrSePlay(24474, 0)
ScrWaitTime(30)
ScrMess(976, 946, "晶子", "「ごしごし、ごしごし……」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24473, 0)
ScrWaitTime(30)
ScrMess(977, 947, "晶子", "「よいしょ、よいしょ……どうですか兄さん、気持ちい<cr>いですか？」")
ScrWaitKey()
ScrWinClear()
ScrBgmPlay(30649, 1)
ScrLbg(29273, 0)
ScrDrawEx(45, 0, 90, 1)
ScrMess(978, 11569, "彰", "「う、うん……き、気持ちいいよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(979, 0, "", "一緒にお風呂に入るだけでも驚いたと言うのに、何と晶<cr>子は背中まで洗ってくれた。")
ScrWaitKey()
ScrWinClear()
ScrMess(980, 0, "", "今日のデートに付き合ってくれたお礼だと言われたが、<cr>こ、これはお礼を貰いすぎじゃないだろうか？")
ScrWaitKey()
ScrWinClear()
ScrMess(981, 948, "晶子", "「どーしたんですか兄さん。さっきから緊張して？　体<cr>カチコチになってますよ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(982, 11570, "彰", "「し、仕方ないだろここはその！　妹とはいえ女の子と<cr>一緒にお風呂に入ってるんだから、自然となるものなん<cr>だよ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(983, 949, "晶子", "「え……何の話です？」")
ScrWaitKey()
ScrWinClear()
ScrMess(984, 11571, "彰", "「へ？　あ、ああ！　そりゃ緊張して固くもなるだろ。<cr>か、可愛い妹がサービスしてくれるんだからさ」")
ScrWaitKey()
ScrWinClear()
ScrMess(985, 950, "晶子", "「ふふふ、サービスなんて大げさですよ。昔はよくこう<cr>してあげてたじゃないですか」")
ScrWaitKey()
ScrWinClear()
ScrMess(986, 951, "晶子", "「本当……懐かしいですね。兄さんの背中、子供のころ<cr>に比べたら随分広くてごつく……」")
ScrWaitKey()
ScrWinClear()
ScrMess(987, 11572, "彰", "「ん？」")
ScrWaitKey()
ScrWinClear()
ScrMess(988, 952, "晶子", "「広くてごつく……なってませんね」")
ScrWaitKey()
ScrWinClear()
ScrMess(989, 953, "晶子", "「むしろ女の子みたいに柔らかくてスベスベで……に、<cr>兄さんって本当に男の子ですか？」")
ScrWaitKey()
ScrWinClear()
ScrMess(990, 11573, "彰", "「ぐうっ！　そ、それを言うなよ。オレだって別になり<cr>たくてなってるわけじゃないんだからな」")
ScrWaitKey()
ScrWinClear()
ScrMess(991, 11574, "彰", "「髭も生えないし、声変わりもしない……友達にもから<cr>かわれて苦労してんだぞ？」")
ScrWaitKey()
ScrWinClear()
ScrMess(992, 954, "晶子", "「あははは、確かにそのせいで、よくお友達と喧嘩に<cr>なってましたね」")
ScrWaitKey()
ScrWinClear()
ScrMess(993, 11575, "彰", "「喧嘩ならまだいいけど、男から告白された時は泣きそ<cr>うになったよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(994, 11576, "彰", "「結局、晶子と間違えてたみたいだからよかったけど、<cr>一瞬血の気が引いて失神しそうになったよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(995, 955, "晶子", "「え？　私に告白って、そんなことありましたっけ？　<cr>ルピナスに行く前ですよね？　いつの話です？」")
ScrWaitKey()
ScrWinClear()
ScrMess(996, 11577, "彰", "「あ……しまった」")
ScrWaitKey()
ScrWinClear()
ScrMess(997, 956, "晶子", "「兄さん、もしかして勝手に断ったんですか！？」")
ScrWaitKey()
ScrWinClear()
ScrMess(998, 11578, "彰", "「だ、だってオレと晶子が区別できないような男だぞ？<cr>そんな奴に晶子と付き合う資格なんてないだろ」")
ScrWaitKey()
ScrWinClear()
ScrMess(999, 957, "晶子", "「それはそうですけど……でも私が好きだなんて貴重な<cr>人、今後出てこないかもしれないのに……」")
ScrWaitKey()
ScrWinClear()
ScrMess(1000, 11579, "彰", "「病院の爺さん達からは好かれてるだろ。それで満足し<cr>ておけよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(1001, 958, "晶子", "「恋愛対象から外れすぎです！　それにおじいちゃん達<cr>の目は完全に孫に対する愛情じゃないですか」")
ScrWaitKey()
ScrWinClear()
ScrMess(1002, 959, "晶子", "「あーあ、私も恋愛小説みたいな恋してみたいな。ラブ<cr>レターも貰ってみたい」")
ScrWaitKey()
ScrWinClear()
ScrMess(1003, 11580, "彰", "「……」")
ScrWaitKey()
ScrWinClear()
ScrMess(1004, 0, "", "そういえば、家に晶子宛のラブレターが届いてその返事<cr>を勝手に出したこともあったな。")
ScrWaitKey()
ScrWinClear()
ScrMess(1005, 0, "", "バスケ部の田代だっけ？　頭もよくていい奴だったが、<cr>電話越しの相手がオレだと気づかないようじゃ失格だ。")
ScrWaitKey()
ScrWinClear()
ScrMess(1006, 0, "", "あれならまだ剣道部の桐沢の方が、晶子の好きな花を持<cr>参してきたりして、気合が入ってた。")
ScrWaitKey()
ScrWinClear()
ScrMess(1007, 0, "", "まあしょせん桐沢も、待ち合わせに来た相手が女装した<cr>オレだって気付けないようなダメ男だったけどな。")
ScrWaitKey()
ScrWinClear()
ScrMess(1008, 960, "晶子", "「兄さん……もしかしてラブレターも勝手に捨てたりし<cr>てませんよね？」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24474, 0)
ScrWinFrame(0)
ScrShake(2, 60)
ScrMess(1009, 11581, "彰", "「ぶへっ！　そ、そんなことするはずないだろ？　じ、<cr>自分がモテないのを兄のせいにするなよ！」")
ScrWaitKey()
ScrWinClear()
ScrMess(1010, 11582, "彰", "「そ、それにラブレターなら最近よく貰ったりするん<cr>じゃないか？　ルピナスの……女の子から」")
ScrWaitKey()
ScrWinClear()
ScrMess(1011, 961, "晶子", "「あはははは……あれはノーカウントですよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(1012, 962, "晶子", "「あの子達は会長に対する憧れと恋愛感情を勘違いして<cr>るだけですから」")
ScrWaitKey()
ScrWinClear()
ScrMess(1013, 963, "晶子", "「恋と憧れは全然違います。そこがまだわかってないん<cr>ですよ……」")
ScrWaitKey()
ScrWinClear()
ScrMess(1014, 11583, "彰", "「どうした？　急に大人な発言だな」")
ScrWaitKey()
ScrWinClear()
ScrMess(1015, 11584, "彰", "「ハッ！　も、もしかして晶子も恋をしたことがあるの<cr>か？　そ、そんなの兄さん初耳だぞ！？」")
ScrWaitKey()
ScrWinClear()
ScrMess(1016, 964, "晶子", "「私はないですけど、お友達に恋をしてる子がいるから<cr>分かるんです」")
ScrWaitKey()
ScrWinClear()
ScrMess(1017, 965, "晶子", "「その子は相手の人に全く気持ちが気付いてもらえなく<cr>て、苦しんで……それだけで恋と憧れが違うことがわか<cr>ります」")
ScrWaitKey()
ScrWinClear()
ScrMess(1018, 11585, "彰", "「ホッ、そうなんだ。しかし晶子の友達を苦しめるなん<cr>て酷い男もいるもんだな」")
ScrWaitKey()
ScrWinClear()
ScrMess(1019, 11586, "彰", "「そんな鈍感男、さっさと見捨てた方がいいんじゃない<cr>か？　何ならオレがその男にガツンと言ってやろう<cr>か？」")
ScrWaitKey()
ScrWinClear()
ScrMess(1020, 966, "晶子", "「ええ、言ってあげてください」")
ScrWaitKey()
ScrWinClear()
ScrMess(1021, 967, "晶子", "「正面に鏡がありますから、好きなだけどうぞ」")
ScrWaitKey()
ScrWinClear()
ScrMess(1022, 11587, "彰", "「へ？　鏡？　それに何の関係が……」")
ScrWaitKey()
ScrWinClear()
ScrMess(1023, 0, "", "理由を聞いてみたが、返ってきたのはため息だった。")
ScrWaitKey()
ScrWinClear()
ScrMess(1024, 0, "", "ど、どうしてため息？　オレ何かしたっけ？")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24473, 0)
ScrMess(1025, 968, "晶子", "「はいこれでおしまい。次は私の背中洗ってください<cr>ね」")
ScrWaitKey()
ScrWinClear()
ScrMess(1026, 11588, "彰", "「え？　オ……オレが晶子を！？　だっ……ダメだよそ<cr>んなこと！」")
ScrWaitKey()
ScrWinClear()
ScrMess(1027, 969, "晶子", "「ぶぅ、どうしてですか。私だけ洗わせるなんてずるい<cr>ですよ」")
ScrWaitKey()
ScrWinClear()
ScrMess(1028, 11589, "彰", "「う……わかった。そ、それじゃあ失礼して……」")
ScrWaitKey()
ScrWinClear()
ScrSePlay(24474, 0)
ScrLbg(28881, 0)
ScrDrawEx(0, 0, 60, 1)
ScrSePlay(24473, 0)
ScrMess(1029, 0, "", "晶子は何気なく背中を見せるが、一般男子であるオレは<cr>その姿にどうしても女性を意識してしまい、洗う手に無<cr>駄な力が入ってしまう。")
ScrWaitKey()
ScrWinClear()
ScrMess(1030, 0, "", "おかげで何度か滑って胸を触りそうになるが、そこは凹<cr>凸のない胸部が幸いして上手くやり過ごすことができ<cr>た。")
ScrWaitKey()
ScrWinClear()
ScrMess(1031, 0, "", "も、もう二度と一緒にお風呂に入るのはやめよう。")
ScrWaitKey()
ScrWinClear()
ScrMess(1032, 0, "", "仲良くしてくれるのは嬉しいけど、オレの体がもたない<cr>よ……")
ScrWaitKey()
ScrWinClear()
ScrSeStop(0)
ScrBgmStop(120)
ScrLbg(28889, 0)
ScrDrawEx(0, 0, 120, 1)
ScrWaitTime(60)
ScrJump(0x0111)
