LABEL 0
FLAG 526, 1
BG 143
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 3671
MESSAGE "お父さん！　大変なの！"
LINE_FEED
MESSAGE "この子が倒れていて……"
KEY_WAIT
VOICE 3672
MESSAGE "お願い！　助けてあげて！"
SELECT 3, 1, "引き離す", 2, "治療を試みる", 3, "自然に任せる"
LABEL 1
FLAG 527, 1
MESSAGE_NAME "[娘の名前]"
VOICE 3673
MESSAGE "お父さん……どうして㌍"
LINE_FEED
MESSAGE "この子が魔獣の子供だから？"
KEY_WAIT
FACE 2
VOICE 3674
MESSAGE "生き物を助けてあげる事は"
LINE_FEED
MESSAGE "いけない事なの？　ねえ……"
LINE_FEED
MESSAGE "お父さん！"
END 0
LABEL 2
FLAG 528, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3675
MESSAGE "どう……？"
LINE_FEED
MESSAGE "この子、大丈夫かな……"
LINE_FEED
MESSAGE "助かる？　ちゃんと……治る？"
KEY_WAIT
VOICE 3676
MESSAGE "ねえ、よくなるんだよ、おまえ。"
LINE_FEED
MESSAGE "私も、ついてて看病するから。"
LINE_FEED
MESSAGE "だから……お願い……！"
END 1
LABEL 3
FLAG 529, 1
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3677
MESSAGE "そんな……いやよ！"
KEY_WAIT
VOICE 3678
MESSAGE "死んじゃう……このままじゃ"
LINE_FEED
MESSAGE "死んじゃうよ、この子。"
KEY_WAIT
VOICE 3679
MESSAGE "この子はまだ生きてるんだよ？"
LINE_FEED
MESSAGE "こうして出会ったんだもの！"
LINE_FEED
MESSAGE "私……助けたいよ！"
END 2
LABEL 4
FLAG 530, 1
BG 144
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3680
MESSAGE "きれいな夕日……"
LINE_FEED
MESSAGE "空もあんなに真っ赤で……"
KEY_WAIT
VOICE 3681
MESSAGE "見えているのは本物なのに……"
LINE_FEED
MESSAGE "まるで絵画を見ているみたいに"
LINE_FEED
MESSAGE "止まって見えるよ……"
SELECT 3, 5, "夕日の方を向く", 6, "娘を見つめる", 7, "夕日が沈むのに見入る"
LABEL 5
FLAG 531, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3682
MESSAGE "あっ……でも、ゆっくりだけど"
LINE_FEED
MESSAGE "お日様が沈んで行くのがわかるね。"
KEY_WAIT
MESSAGE "…………………"
LINE_FEED
MESSAGE "…………"
LINE_FEED
MESSAGE "………"
KEY_WAIT
FACE 1
VOICE 3683
MESSAGE "はあ～っ……"
LINE_FEED
MESSAGE "きれいだったね、お父さん。"
END 0
LABEL 6
FLAG 532, 1
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 3684
MESSAGE "……お父さん、どうしたの？"
LINE_FEED
MESSAGE "私の顔……何かついてる？"
LINE_FEED
MESSAGE "は、恥ずかしいよ……"
END 1
LABEL 7
FLAG 533, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3685
MESSAGE "お父さん……？"
LINE_FEED
MESSAGE "寒くなってきたから、"
LINE_FEED
MESSAGE "そろそろ行こうよ。"
KEY_WAIT
VOICE 3686
MESSAGE "わ、お父さんの体も冷え切ってる。"
LINE_FEED
MESSAGE "そうだ。風邪ひかないように、"
LINE_FEED
MESSAGE "私が暖めてあげるね㍍"
KEY_WAIT
FACE 6
VOICE 3687
MESSAGE "ふふふ……暖かいでしょ。"
LINE_FEED
MESSAGE "さあ、行こっ。"
END 2
LABEL 8
FLAG 534, 1
BG 145
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3688
MESSAGE "木や草の香りを感じながらの"
LINE_FEED
MESSAGE "読書。たまにはこういう所で"
LINE_FEED
MESSAGE "くつろぐのもいいね、お父さん。"
SELECT 3, 9, "一緒に本を読む", 10, "エサをやる", 11, "寝る"
LABEL 9
FLAG 535, 1
MESSAGE_NAME "[娘の名前]"
VOICE 3689
MESSAGE "ふふふ……"
LINE_FEED
MESSAGE "ねぇねぇ、この本面白いよ㍍"
LINE_FEED
MESSAGE "お父さんは何読んでるの？"
KEY_WAIT
FACE 4
VOICE 3690
MESSAGE "どれどれ……わわっ、ずいぶん"
LINE_FEED
MESSAGE "難しいご本を読んでるんだね。"
LINE_FEED
MESSAGE "すごーい……"
END 0
LABEL 10
FLAG 536, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3691
MESSAGE "エサ？　ああ、動物たちに"
LINE_FEED
MESSAGE "エサをあげるのね？"
KEY_WAIT
VOICE 3692
MESSAGE "ほーら、おいで……"
KEY_WAIT
FACE 1
VOICE 3693
MESSAGE "きゃあ、いっぱい来ちゃった㌍"
LINE_FEED
MESSAGE "でも、かわいい㍍"
END 1
LABEL 11
FLAG 537, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3694
MESSAGE "あれ……お父さん？"
LINE_FEED
MESSAGE "寝ちゃったの？"
KEY_WAIT
VOICE 3695
MESSAGE "……うふふ、寝顔かわいい。"
LINE_FEED
MESSAGE "ふぁ～……私も"
LINE_FEED
MESSAGE "眠くなっちゃった……"
END 2
LABEL 12
FLAG 538, 1
BG 146
FACE 8
MESSAGE_NAME "[娘の名前]"
VOICE 3696
MESSAGE "厳しい冬の海……"
KEY_WAIT
VOICE 3697
MESSAGE "ここはなんだか寂しくて、"
LINE_FEED
MESSAGE "とても悲しい感じがする。"
LINE_FEED
MESSAGE "ここには何もないもの……"
SELECT 3, 13, "１人にしとく", 14, "肩をよせる", 15, "呼び寄せる"
LABEL 13
FLAG 539, 1
MESSAGE_NAME "[娘の名前]"
MESSAGE "…………"
KEY_WAIT
VOICE 3698
MESSAGE "（刺すように冷たい風……"
LINE_FEED
MESSAGE "岩を削ろうと荒れる波……）"
KEY_WAIT
VOICE 3699
MESSAGE "（何もないように見えたけれど……"
LINE_FEED
MESSAGE "ここには甘えを寄せ付けない"
LINE_FEED
MESSAGE "自然の厳しさがある……）"
END 0
LABEL 14
FLAG 540, 1
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3700
MESSAGE "私……なんだか怖いの。"
LINE_FEED
MESSAGE "ぼうっとしていると、冷たい波に"
LINE_FEED
MESSAGE "さらわれてしまいそうで……"
KEY_WAIT
FACE 0
VOICE 3701
MESSAGE "しっかり抱きとめていてね、"
LINE_FEED
MESSAGE "お父さん……"
END 1
LABEL 15
FLAG 541, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3702
MESSAGE "……え？　なに、お父さん？"
KEY_WAIT
VOICE 3703
MESSAGE "あ……そうね。"
LINE_FEED
MESSAGE "そろそろ帰りましょうか。"
KEY_WAIT
VOICE 3704
MESSAGE "なんだか引き込まれちゃってた"
LINE_FEED
MESSAGE "みたい。ちょっと怖かったな……"
END 2