LABEL 0
FLAG 669, 1
LABEL 1
FLAG 670, 1
BGM_STOP 30
BGM_PLAY 17
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "旦那様、旦那様！"
LINE_FEED
MESSAGE "大変です、お嬢様が家の外で、"
LINE_FEED
MESSAGE "他の子供たちに！"
KEY_WAIT
BG 58
FACE 65535
MESSAGE_NAME "男の子Ａ"
MESSAGE "なんだよ、俺達とは"
LINE_FEED
MESSAGE "遊べないってか？"
KEY_WAIT
MESSAGE_NAME "男の子Ｂ"
MESSAGE "カッコつけてんじゃねぇぞ！"
KEY_WAIT
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 435
MESSAGE "もう、かまわないで。"
LINE_FEED
MESSAGE "今、おうちのお使いに"
LINE_FEED
MESSAGE "行くところなんだから～"
KEY_WAIT
FACE 65535
MESSAGE_NAME "男の子Ａ"
MESSAGE "俺達と遊ぶ方が大事だろ～"
KEY_WAIT
MESSAGE_NAME "男の子Ｂ"
MESSAGE "ほら、来いよ。"
KEY_WAIT
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 436
MESSAGE "そ、そんなこと……"
KEY_WAIT
FACE 65535
MESSAGE_NAME "女の子Ａ"
MESSAGE "むっ。お高くとまってんじゃ"
LINE_FEED
MESSAGE "ないわよ？"
KEY_WAIT
MESSAGE_NAME "男の子Ａ"
MESSAGE "いじめちゃうぞ、おら！"
KEY_WAIT
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 437
MESSAGE "う、ううっ～"
LINE_FEED
MESSAGE "じゃあ、お使い行った後でなら……"
KEY_WAIT
FACE 65535
MESSAGE_NAME "男の子Ｂ"
MESSAGE "ダ～メ、今すぐ。"
LINE_FEED
MESSAGE "ほら、こっち来いよ！"
KEY_WAIT
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 438
MESSAGE "キャーッ！"
LINE_FEED
MESSAGE "何すんのっ㌍"
KEY_WAIT
FACE 65535
MESSAGE_NAME "女の子Ａ"
MESSAGE "フン。あんたのお母さん、"
LINE_FEED
MESSAGE "あんたが嫌で家出たらしい"
LINE_FEED
MESSAGE "じゃない。"
KEY_WAIT
MESSAGE "そんな強情なところが"
LINE_FEED
MESSAGE "嫌われたんじゃないの？"
KEY_WAIT
FACE 8
MESSAGE_NAME "[娘の名前]"
VOICE 439
MESSAGE "えっ㌍"
LINE_FEED
MESSAGE "なんで……そんなこと……"
LINE_FEED
MESSAGE "か、関係ないじゃない！"
KEY_WAIT
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "ど、どうしましょうか"
LINE_FEED
MESSAGE "旦那様っ㌍　こうしている"
LINE_FEED
MESSAGE "間にもお嬢様が……"
SELECT 2, 2, "助ける", 3, "見守る"
LABEL 2
END 0
LABEL 3
END 1
LABEL 4
FLAG 671, 1
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "わっかりました！"
LINE_FEED
MESSAGE "不肖、このキューブも"
LINE_FEED
MESSAGE "お手伝いいたします！"
KEY_WAIT
MESSAGE "こら、この悪ガキども～！"
KEY_WAIT
FACE 65535
MESSAGE_NAME "男の子Ａ"
MESSAGE "うわ、[娘の名前]の"
LINE_FEED
MESSAGE "親が出てきたぞ、逃げろ～！！"
KEY_WAIT
MESSAGE_NAME "男の子Ｂ"
SE_PLAY 7
MESSAGE "わぁ～っ！！"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "ちぇーっ、逃げ足の早い……"
KEY_WAIT
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 440
MESSAGE "うっく、ひっく……"
KEY_WAIT
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "あっ、お嬢様！　大丈夫ですか？"
LINE_FEED
MESSAGE "おケガは……"
KEY_WAIT
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 441
MESSAGE "パパ……"
LINE_FEED
MESSAGE "どうして、私には"
LINE_FEED
MESSAGE "お母さんがいないの？"
KEY_WAIT
VOICE 442
MESSAGE "お母さんに……会いたいよぅ……"
LINE_FEED
MESSAGE "うううっ、ぐすん……"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "お嬢様……"
KEY_WAIT
BGM_STOP 30
OFF_CHAR 3
OFF_FACE_WINDOW
FACE 65535
BG 0
END 0
LABEL 5
FLAG 672, 1
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "ええっ㌍"
LINE_FEED
MESSAGE "しかし、旦那様……"
KEY_WAIT
FACE 28
MESSAGE "……わかりました。"
KEY_WAIT
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 443
MESSAGE "……こと、ない……"
KEY_WAIT
FACE 65535
MESSAGE_NAME "男の子Ａ"
MESSAGE "……？"
KEY_WAIT
FACE 8
MESSAGE_NAME "[娘の名前]"
VOICE 444
MESSAGE "そんなこと……ないもんっ！"
KEY_WAIT
VOICE 445
MESSAGE "お、お母さんが私のこと嫌いだから"
LINE_FEED
MESSAGE "出ていったなんて、そんなこと……"
KEY_WAIT
FACE 2
VOICE 446
MESSAGE "そんなこと、"
LINE_FEED
MESSAGE "絶対にないんだからーっ！"
LINE_FEED
MESSAGE "ばかぁぁぁぁ！！"
KEY_WAIT
FACE 65535
MESSAGE_NAME "女の子Ａ"
MESSAGE "きゃーっ！"
KEY_WAIT
MESSAGE_NAME "男の子Ｂ"
MESSAGE "うわ、[娘の名前]が怒ったぞ㌍"
KEY_WAIT
MESSAGE_NAME "男の子Ａ"
SE_PLAY 7
MESSAGE "にげろ～っ！！"
KEY_WAIT
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 447
MESSAGE "はぁ……はぁ……"
KEY_WAIT
FACE 3
VOICE 448
MESSAGE "お母さん……"
LINE_FEED
MESSAGE "ぐすん……"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "お嬢様……"
KEY_WAIT
BGM_STOP 30
OFF_CHAR 3
OFF_FACE_WINDOW
FACE 65535
BG 0
END 0