LABEL 0
FLAG 277, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "やあ、はじめまして[娘の名前]。"
LINE_FEED
MESSAGE "わしはレロン・プリスコフ。"
LINE_FEED
MESSAGE "芸術一般を教えておる。"
KEY_WAIT
MESSAGE "絵画、彫刻、そして文学……"
LINE_FEED
MESSAGE "芸術とは豊かな文化の源にして"
LINE_FEED
MESSAGE "結実でもあるのだよ。"
KEY_WAIT
MESSAGE "そして、次代を担う君たち若者にも"
LINE_FEED
MESSAGE "そのすばらしさを存分に知り、"
LINE_FEED
MESSAGE "学びとってほしい……"
KEY_WAIT
MESSAGE "さあ、君もその心のほとばしりを、"
LINE_FEED
MESSAGE "思うままキャンバスに"
LINE_FEED
MESSAGE "叩きつけようではないか！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "よ、よろしくお願いします……"
KEY_WAIT
MESSAGE "（なんだか、"
LINE_FEED
MESSAGE "勢いのいい先生だなぁ……）"
KEY_WAIT
END 0
LABEL 1
FLAG 278, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "やあ、来たかね、[娘の名前]。"
LINE_FEED
MESSAGE "では今回も、共に美のなんたるかを"
LINE_FEED
MESSAGE "追求しようじゃないか！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "よろしくお願いします、先生。"
KEY_WAIT
END 0
LABEL 2
FLAG 279, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "いやいやいや…これは素晴らしい！"
LINE_FEED
MESSAGE "どうやら今の君には芸術の神が"
LINE_FEED
MESSAGE "降りてきているようだな！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "そんな……たまたまですよ……"
LINE_FEED
MESSAGE "でも、ありがとうございます。"
LINE_FEED
MESSAGE "なんだか自信が持てそうです。"
KEY_WAIT
END 0
LABEL 3
FLAG 280, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "うわぁ、すっごぉ～い……"
LINE_FEED
MESSAGE "全部、完璧だったよ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3472
MESSAGE "アハハ……"
LINE_FEED
MESSAGE "なんだかうまくいっちゃったわ。"
LINE_FEED
MESSAGE "今日は調子がいいみたい。"
KEY_WAIT
END 0
LABEL 4
FLAG 281, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "[娘の名前]ちゃん、すごいよ！"
LINE_FEED
MESSAGE "きっと才能があるのね。"
LINE_FEED
MESSAGE "うらやましいなぁ……"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3473
MESSAGE "さ、才能だなんて大げさよ。"
LINE_FEED
MESSAGE "たまたま、うまくいっただけだわ。"
LINE_FEED
MESSAGE "でも、ありがとね。"
KEY_WAIT
END 0
LABEL 5
FLAG 282, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "すごいなぁ。"
LINE_FEED
MESSAGE "私も、見習わなくちゃ……"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3474
MESSAGE "私だってまだまだよ。"
LINE_FEED
MESSAGE "お互い、もっと頑張らないとね。"
KEY_WAIT
END 0
LABEL 6
FLAG 283, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "うむむむ……"
LINE_FEED
MESSAGE "どうやら不調のようだね。"
KEY_WAIT
MESSAGE "無理をしてもいいことはない。"
LINE_FEED
MESSAGE "今日は帰って休んではどうかな？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "うーん、スランプなのかなぁ……"
KEY_WAIT
END 0
LABEL 7
FLAG 284, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "だ、大丈夫？"
LINE_FEED
MESSAGE "[娘の名前]ちゃん……"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3475
MESSAGE "ううっ……"
LINE_FEED
MESSAGE "大失敗……"
KEY_WAIT
END 0
LABEL 8
FLAG 285, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "あ、あらら～……"
LINE_FEED
MESSAGE "もしかして、調子悪いの？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3476
MESSAGE "あうっ……"
LINE_FEED
MESSAGE "これじゃ、お父さんに"
LINE_FEED
MESSAGE "怒られちゃうよぉ……"
KEY_WAIT
END 0
LABEL 9
FLAG 286, 1
FACE 17
MESSAGE_NAME "マリー"
MESSAGE "ね、ねえ……"
LINE_FEED
MESSAGE "大丈夫……？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3477
MESSAGE "お、お願い……"
LINE_FEED
MESSAGE "何も言わないで……"
KEY_WAIT
END 0
LABEL 10
FLAG 287, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "よし、それでは今回はここまで。"
LINE_FEED
MESSAGE "次も頑張ってくれ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はい、ありがとうございました、"
LINE_FEED
MESSAGE "レロン先生。"
KEY_WAIT
END 0
LABEL 11
FLAG 288, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "君はなかなか筋がいいな。"
LINE_FEED
MESSAGE "わしも教え甲斐が"
LINE_FEED
MESSAGE "あるというものだよ。"
KEY_WAIT
MESSAGE "どれ、次回からは"
LINE_FEED
MESSAGE "新しい技法についての"
LINE_FEED
MESSAGE "講義をしてみようか。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はいっ、よろしくお願いします！"
KEY_WAIT
END 0
LABEL 12
FLAG 289, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "やあ、[娘の名前]。君もすっかり"
LINE_FEED
MESSAGE "いっぱしの芸術家の風情に"
LINE_FEED
MESSAGE "なったな。喜ばしいことだ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "先生……"
LINE_FEED
MESSAGE "そんな、私なんてまだまだで……"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "いやいや、謙遜する必要はない。"
LINE_FEED
MESSAGE "そこで、ひとつ君に課題を"
LINE_FEED
MESSAGE "出したいと思う。"
KEY_WAIT
MESSAGE "まあ、卒業試験と"
LINE_FEED
MESSAGE "思ってくれればいい。"
KEY_WAIT
MESSAGE "これに合格できれば、"
LINE_FEED
MESSAGE "君も一人前ということだ。"
LINE_FEED
MESSAGE "どうだね、やってみるかい？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "私が一人前に……"
KEY_WAIT
MESSAGE "わかりました、先生。"
LINE_FEED
MESSAGE "私、試験を受けます！"
KEY_WAIT
MESSAGE "先生に認めてもらえるように"
LINE_FEED
MESSAGE "頑張りますから！"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "うん、いい返事だ。"
LINE_FEED
MESSAGE "では、さっそく卒業試験を"
LINE_FEED
MESSAGE "行うことにしよう。"
KEY_WAIT
MESSAGE "頑張りたまえ！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はいっ！"
KEY_WAIT
BG 176
MESSAGE "…………"
KEY_WAIT
BG 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "うむむむ……"
KEY_WAIT
MESSAGE "むむむむむ……"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "……あの、レロン先生？"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ふう～む……"
KEY_WAIT
MESSAGE "見事だ……この短期間で、"
LINE_FEED
MESSAGE "よくここまでのものを"
LINE_FEED
MESSAGE "創りあげたね。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "そ、それじゃ……"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "文句なく合格だ。"
LINE_FEED
MESSAGE "これなら、ひとりでも立派に"
LINE_FEED
MESSAGE "やっていくことができるだろう。"
KEY_WAIT
MESSAGE "おめでとう！"
LINE_FEED
MESSAGE "ああ、わしは今ここに、ひとりの"
LINE_FEED
MESSAGE "芸術家の誕生を祝福しよう！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "レロン先生……"
LINE_FEED
MESSAGE "ありがとうございます！"
LINE_FEED
MESSAGE "これも先生のおかげですっ。"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "これからは君も、儂のライバルだ。"
LINE_FEED
MESSAGE "共に切磋琢磨し、美の道を"
LINE_FEED
MESSAGE "歩み続けようじゃないか！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はいっ！"
KEY_WAIT
END 0
LABEL 13
FLAG 290, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ああ、[娘の名前]。"
LINE_FEED
MESSAGE "ちょっと頼みがあるのだが、"
LINE_FEED
MESSAGE "いいかね？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "どうしたんですか、先生？"
LINE_FEED
MESSAGE "頼み事って？"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ああ、君にわしの講座の助手を"
LINE_FEED
MESSAGE "やってほしいんだよ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "私が、先生の助手を㌍"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ああ、そうだ。君は筋もいいし、"
LINE_FEED
MESSAGE "誰かに教えることで自身の技術も"
LINE_FEED
MESSAGE "いっそう上がるだろう。"
KEY_WAIT
MESSAGE "もちろん、助手としての"
LINE_FEED
MESSAGE "給金も払おう。"
KEY_WAIT
MESSAGE "空いてる時間は文章を作るなり、"
LINE_FEED
MESSAGE "絵を描くなり好きに使うといい。"
KEY_WAIT
MESSAGE "どうだね？"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "先生がそうおっしゃるのなら……"
LINE_FEED
MESSAGE "未熟ですが、助手を"
LINE_FEED
MESSAGE "つとめさせてもらいます。"
KEY_WAIT
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ああ、さっそく頼むよ。"
KEY_WAIT
END 0
LABEL 14
FLAG 291, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "やあ、今回もよろしく頼むよ。"
LINE_FEED
MESSAGE "共に芸術のすばらしさを"
LINE_FEED
MESSAGE "広めようじゃないか。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はい、頑張りましょう、先生！"
KEY_WAIT
END 0
LABEL 15
FLAG 292, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "うむうむ、君は生徒としても"
LINE_FEED
MESSAGE "優秀だが、教師としても"
LINE_FEED
MESSAGE "なかなかのものだな。"
KEY_WAIT
MESSAGE "生徒たちにも評判がいい様子で"
LINE_FEED
MESSAGE "なによりだ。"
KEY_WAIT
MESSAGE "それに、今取り掛かってる作品。"
LINE_FEED
MESSAGE "なかなかの出来のようだな。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "ありがとうございます、先生。"
KEY_WAIT
END 0
LABEL 16
FLAG 293, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "いやあ、君にこういうことを"
LINE_FEED
MESSAGE "頼むのは、まだ早かったかな？"
KEY_WAIT
MESSAGE "作品を作るということは、"
LINE_FEED
MESSAGE "そんなに簡単なものじゃ"
LINE_FEED
MESSAGE "ないんだよ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "うう……芸術の道って、厳しい……"
KEY_WAIT
END 0
LABEL 17
FLAG 294, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "やあ、お疲れさま、[娘の名前]。"
LINE_FEED
MESSAGE "次回もこの調子で頼むよ。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "はい、こちらこそ"
LINE_FEED
MESSAGE "よろしくお願いしますね、先生。"
KEY_WAIT
END 0
LABEL 18
FLAG 295, 1
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "これまで、君も数々の技法を学んで"
LINE_FEED
MESSAGE "きたはずだ。"
KEY_WAIT
MESSAGE "１００Ｇかかるが、ひとつ作品に"
LINE_FEED
MESSAGE "挑戦して、その成果を見せてみては"
LINE_FEED
MESSAGE "どうかね？"
SELECT 2, 19, "はい", 22, "いいえ"
LABEL 19
END 0
LABEL 20
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "ふむ、お金が足りないようだな。"
LINE_FEED
MESSAGE "この話は、また次の機会にしよう。"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
MESSAGE "うう……芸術の道って、厳しい……"
KEY_WAIT
END 0
LABEL 21
FACE 65535
OFF_FACE_WINDOW
MESSAGE "[娘の名前]は作品制作に"
LINE_FEED
MESSAGE "取り組んだ……"
KEY_WAIT
END 0
LABEL 22
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "そうか、まだ自分の絵を描く気に"
LINE_FEED
MESSAGE "ならんか……"
KEY_WAIT
END 1
LABEL 23
FACE 50
MESSAGE_NAME "レロン"
MESSAGE "次回はしっかり"
LINE_FEED
MESSAGE "授業料を払ってくれよ。"
KEY_WAIT
END 0