LABEL 0
CHAR 0, 1
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 1
SE_PLAY 6
SE_WAIT
SE_PLAY 1
SE_WAIT
SE_PLAY 3
SE_WAIT
BGM_PLAY 22
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "失礼します旦那様、"
LINE_FEED
MESSAGE "執事のキューブです。"
KEY_WAIT
FACE 26
MESSAGE "お嬢様は今日も元気です。"
KEY_WAIT
MESSAGE "いつの間にか"
LINE_FEED
MESSAGE "お嬢様も大きくなられましたねぇ…"
KEY_WAIT
FACE 25
MESSAGE "でも、これからが難しい"
LINE_FEED
MESSAGE "年頃なのかもしれません。"
KEY_WAIT
FACE 23
MESSAGE "よりいっそう注意して"
LINE_FEED
MESSAGE "お育てしないといけませんね。"
KEY_WAIT
MESSAGE "お嬢様の今後の育成について"
LINE_FEED
MESSAGE "なにかご相談は"
LINE_FEED
MESSAGE "ございますでしょうか？"
SELECT 2, 3, "はい", 2, "いいえ"
LABEL 2
MESSAGE "わかりました。"
KEY_WAIT
GOTO 4
LABEL 3
SPECIAL 0
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "それでは、下画面を見ながら説明を"
LINE_FEED
MESSAGE "きいていただけますか？"
KEY_WAIT
SPECIAL 1
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "「Ｈｅａｌｔｈ」では、"
LINE_FEED
MESSAGE "基本的な育成方針が決められます。"
KEY_WAIT
MESSAGE "ここでの調整は、健康状態の他、"
LINE_FEED
MESSAGE "お嬢様の身長や体重、スリーサイズ"
LINE_FEED
MESSAGE "などに反映されることになります。"
KEY_WAIT
SPECIAL 2
SPECIAL 3
FACE 23
MESSAGE "「活発に育てる」では、"
LINE_FEED
MESSAGE "養育費がかかりますが"
LINE_FEED
MESSAGE "丈夫に育てられます。"
KEY_WAIT
MESSAGE "ただし、食べすぎには"
LINE_FEED
MESSAGE "気をつけてください。"
KEY_WAIT
SPECIAL 4
FACE 23
MESSAGE "「ダイエットさせる」は"
LINE_FEED
MESSAGE "体力に負担をかけますので"
LINE_FEED
MESSAGE "注意してください。"
KEY_WAIT
SPECIAL 5
FACE 23
MESSAGE "「おしとやかに育てる」は、"
LINE_FEED
MESSAGE "それほど養育費はかかりません。"
KEY_WAIT
MESSAGE "ただし、体力に自信がない場合は"
LINE_FEED
MESSAGE "お勧めできません。"
KEY_WAIT
SPECIAL 11
FACE 26
MESSAGE "普段は「無理はさせない」で"
LINE_FEED
MESSAGE "よいと思います。"
KEY_WAIT
SPECIAL 0
SPECIAL 6
FACE 23
MESSAGE "「Ｓｃｈｅｄｕｌｅ」でお嬢様の"
LINE_FEED
MESSAGE "月の行動を決めてください。"
KEY_WAIT
SPECIAL 7
SPECIAL 8
FACE 23
MESSAGE "「勉強」でお嬢様の才能を"
LINE_FEED
MESSAGE "伸ばしたり「アルバイト」で"
LINE_FEED
MESSAGE "社会勉強するのもいいですね。"
KEY_WAIT
SPECIAL 9
FACE 26
MESSAGE "でも、お休みに街へ出かけて"
LINE_FEED
MESSAGE "世間を知ることやバカンスでの"
LINE_FEED
MESSAGE "親子のふれあいも大切ですよ。"
KEY_WAIT
FACE 23
MESSAGE "その行動でどのくらいお金がかかる"
LINE_FEED
MESSAGE "か、またはアルバイトでどのくらい"
LINE_FEED
MESSAGE "稼げるか所持金欄に表示されます。"
KEY_WAIT
SPECIAL 12
MESSAGE "あくまで、だいたいの目安ですが、"
LINE_FEED
MESSAGE "参考にしてくださいね。"
KEY_WAIT
SPECIAL 0
SPECIAL 13
MESSAGE "「Ｔａｌｋ」でお嬢様とお話が"
LINE_FEED
MESSAGE "できます。"
KEY_WAIT
FACE 26
MESSAGE "お嬢様を寂しがらせぬよう、"
LINE_FEED
MESSAGE "毎月１度はお話してさしあげて"
LINE_FEED
MESSAGE "くださいね。"
KEY_WAIT
SPECIAL 14
FACE 23
MESSAGE "お嬢様の状態を考えて、適切な"
LINE_FEED
MESSAGE "会話をしてあげてください。"
KEY_WAIT
MESSAGE "何が適切かを知るのも、親として"
LINE_FEED
MESSAGE "重要だと思いますよ。"
KEY_WAIT
SPECIAL 0
SPECIAL 15
MESSAGE "「Ｓｔａｔｕｓ」で、お嬢様の"
LINE_FEED
MESSAGE "現在の状態がわかります。"
KEY_WAIT
SPECIAL 10
MESSAGE "このメニュー以外でもお嬢様の"
LINE_FEED
MESSAGE "状態は表示されていますので"
LINE_FEED
MESSAGE "常に参考して下さい。"
KEY_WAIT
MESSAGE "また、この画面でＬキーかＲキーを"
LINE_FEED
MESSAGE "押すことで、画面上部の表示を"
LINE_FEED
MESSAGE "切り替えることができます。"
KEY_WAIT
SPECIAL 0
MESSAGE "この画面でも切り替えは可能です。"
LINE_FEED
MESSAGE "全部で４行あるうち、３行が表示"
LINE_FEED
MESSAGE "されます。"
KEY_WAIT
MESSAGE "必要に応じて切り替えて下さい。"
KEY_WAIT
SPECIAL 10
MESSAGE "また、Ｙボタンを押すことで"
LINE_FEED
MESSAGE "ウィンドウを消して、下の画面を"
LINE_FEED
MESSAGE "見ることができます。"
KEY_WAIT
MESSAGE "ただしハートマークの絵が出ている"
LINE_FEED
MESSAGE "時しか消すことができませんので"
LINE_FEED
MESSAGE "注意して下さいね。"
KEY_WAIT
MESSAGE "Ｘボタンはメッセージを高速で"
LINE_FEED
MESSAGE "早送りします。一度読んだ所とかで"
LINE_FEED
MESSAGE "使えば便利だと思います。"
KEY_WAIT
LABEL 4
FACE 65535
OFF_FACE_WINDOW
MESSAGE "　　　　　　　　・　　　　　　　"
LINE_FEED
MESSAGE "　　　　　　　　・　　　　　　　"
LINE_FEED
MESSAGE "　　　　　　　　・　　　　　　　"
KEY_WAIT
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
BGM_STOP 60
FACE 65535
MESSAGE_NAME "[娘の名字]"
MESSAGE "このキューブは、"
LINE_FEED
MESSAGE "[娘の名前]を引き取った時に"
LINE_FEED
MESSAGE "執事として主従の契約をした。"
KEY_WAIT
MESSAGE "その契約とは、"
LINE_FEED
MESSAGE "娘の行動を見守ること。"
KEY_WAIT
MESSAGE "そしてその行動を、私に"
LINE_FEED
MESSAGE "うそ偽りなく報告することだ。"
KEY_WAIT
MESSAGE "契約を違えることなく"
LINE_FEED
MESSAGE "何かと役に立ってくれている。"
KEY_WAIT
MESSAGE "イザベルは、[娘の名前]と"
LINE_FEED
MESSAGE "キューブを託した。"
KEY_WAIT
MESSAGE "将来[娘の名前]が"
LINE_FEED
MESSAGE "大きくなったとき、イザベルと会う"
LINE_FEED
MESSAGE "機会ができるだろうか？"
KEY_WAIT
MESSAGE "そんな時でも"
LINE_FEED
MESSAGE "自分の複雑な境遇を受け止め、"
LINE_FEED
MESSAGE "負けない子に育って欲しい。"
KEY_WAIT
MESSAGE "立派な大人に育てなければ……"
LINE_FEED
MESSAGE "私の残りの人生は"
LINE_FEED
MESSAGE "娘のためにあるのだから……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
SE_PLAY 1
SE_WAIT
SE_PLAY 3
SE_WAIT
ROOM_BGM_PLAY
CHAR 0, 2
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 2668
MESSAGE "パパ、おはよう！"
LINE_FEED
MESSAGE "今日はとってもいい天気"
LINE_FEED
MESSAGE "気持ちいいねぇ～"
KEY_WAIT
VOICE 2669
MESSAGE "私もパパと一緒にがんばるぞー"
LINE_FEED
MESSAGE "あははっ！"
KEY_WAIT
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "さて、旦那様"
LINE_FEED
MESSAGE "最初に何をなさいますか？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 5
CHAR 0, 0
FACE 65535
OFF_FACE_WINDOW
MESSAGE "娘が病気になった。"
KEY_WAIT
END 0
LABEL 6
CHAR 0, 0
FACE 65535
OFF_FACE_WINDOW
MESSAGE "娘が不良になった。"
LINE_FEED
MESSAGE "いくつかのバイトが"
LINE_FEED
MESSAGE "できなくなった。"
KEY_WAIT
END 0
LABEL 7
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "だっ、旦那様！　今しがた、"
LINE_FEED
MESSAGE "お嬢様が倒られましたよっ㌍"
LINE_FEED
MESSAGE "あ、はいっ。幸い大事には……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
END 0
LABEL 8
FLAG 1702, 1
CHAR 0, 0
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "最近、お嬢様の体調が思わしくない"
LINE_FEED
MESSAGE "ようです。少し、お休みさせて"
LINE_FEED
MESSAGE "あげてはいかがでしょうか。"
KEY_WAIT
MESSAGE "私は魔族ですが、病魔はやはり"
LINE_FEED
MESSAGE "嫌いですから……はい。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
END 0
LABEL 9
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "旦那様！"
LINE_FEED
MESSAGE "お嬢様が、全快なされました！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
END 0
LABEL 10
FLAG 1703, 1
CHAR 0, 0
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "旦那様。"
LINE_FEED
MESSAGE "最近、お嬢様の素行がよろしくない"
LINE_FEED
MESSAGE "という評判が聞こえてまいります。"
KEY_WAIT
MESSAGE "わたしにも最近冷たいというか"
LINE_FEED
MESSAGE "よそよそしいと言いますか……"
LINE_FEED
MESSAGE "お話もそっけ無くて…ううっ……"
KEY_WAIT
MESSAGE "やはりお嬢様の心を開く事が"
LINE_FEED
MESSAGE "できるのは旦那様です。"
LINE_FEED
MESSAGE "どうか、よろしくお願いします。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
END 0
LABEL 11
CHAR 0, 1
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "旦那様、た、大変です！"
LINE_FEED
MESSAGE "お嬢様がなんだか悪い子に～！"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 2502
MESSAGE "キューブ、うるさい！"
LINE_FEED
MESSAGE "私のことはほっといてよー！"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "そ、そんなぁ……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 1
END 0
LABEL 12
CHAR 0, 1
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "旦那様、た、大変です！"
LINE_FEED
MESSAGE "お嬢様が、お嬢様が"
LINE_FEED
MESSAGE "不良にい～っ……㌍"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 2503
MESSAGE "うるさいわよキューブ！"
LINE_FEED
MESSAGE "私がどうなろうと貴方には"
LINE_FEED
MESSAGE "関係ないでしょう？"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "そ、そんなぁ……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 1
END 0
LABEL 13
CHAR 0, 1
FACE 24
MESSAGE_NAME "キューブ"
MESSAGE "旦那様、た、大変です！"
LINE_FEED
MESSAGE "お嬢様が……お嬢様が……"
KEY_WAIT
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 2504
MESSAGE "騒ぐような事じゃないわよ、"
LINE_FEED
MESSAGE "キューブ。私がどうなろうと、"
LINE_FEED
MESSAGE "私の勝手よ。"
KEY_WAIT
VOICE 2505
MESSAGE "そう、みんな自分勝手。"
LINE_FEED
MESSAGE "お父様だって……"
KEY_WAIT
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "そ、そんなぁ……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 1
END 0
LABEL 14
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2506
MESSAGE "キューブ。あ、あの、この前は"
LINE_FEED
MESSAGE "ひどい事言っちゃって、ごめんね。"
KEY_WAIT
FACE 27
MESSAGE_NAME "キューブ"
MESSAGE "お嬢様……"
LINE_FEED
MESSAGE "そんな、いいんですよ。"
LINE_FEED
MESSAGE "気にしないでくださいね。"
KEY_WAIT
CHAR 0, 2
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 2507
MESSAGE "うん♪　ありがとねっ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 0
END 0
LABEL 15
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2508
MESSAGE "ごめんなさい、キューブ。"
LINE_FEED
MESSAGE "この前の私、どうかしてた……"
KEY_WAIT
FACE 27
MESSAGE_NAME "キューブ"
MESSAGE "お顔をあげて下さい、お嬢様。"
LINE_FEED
MESSAGE "私は気にしていませんから。"
LINE_FEED
MESSAGE "でも、ちょっとホッとしました。"
KEY_WAIT
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2509
MESSAGE "心配させちゃってるよね、"
LINE_FEED
MESSAGE "キューブ。"
LINE_FEED
MESSAGE "ごめんなさい……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 0
END 0
LABEL 16
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2510
MESSAGE "キューブ、ごめんなさい。"
LINE_FEED
MESSAGE "貴方のこと考えないで、私……"
LINE_FEED
MESSAGE "ひどい事言っちゃって……"
KEY_WAIT
FACE 27
MESSAGE_NAME "キューブ"
MESSAGE "いえいえ。正直な気持ちを"
LINE_FEED
MESSAGE "ぶつけて下さって、わたしは"
LINE_FEED
MESSAGE "うれしく思います。"
KEY_WAIT
MESSAGE "これからも無理はなさらないで。"
LINE_FEED
MESSAGE "つらかった時は、またわたしに"
LINE_FEED
MESSAGE "あたって下さい。ね、お嬢様。"
KEY_WAIT
CHAR 0, 7
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 2511
MESSAGE "……キューブ。私……貴方が"
LINE_FEED
MESSAGE "そばに居てくれて、本当に"
LINE_FEED
MESSAGE "良かった……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
CHAR 0, 0
END 0
LABEL 17
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2687
MESSAGE "パパ、わたしの誕生日おぼえてる？"
LINE_FEED
MESSAGE "悪い子だからお祝いして"
LINE_FEED
MESSAGE "もらえないのかなぁ…"
KEY_WAIT
CHAR 0, 0
END 0
LABEL 18
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2648
MESSAGE "今年の誕生日は、"
LINE_FEED
MESSAGE "なんだかさびしいわ………"
MESSAGE "　　　　　　　　　　　"
MESSAGE "私のことなんて興味ないのかしら…"
KEY_WAIT
CHAR 0, 0
END 0
LABEL 19
CHAR 0, 8
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 2619
MESSAGE "お父様、贅沢なんて言わないけど"
LINE_FEED
MESSAGE "誕生日って特別なものだと思うわ…"
KEY_WAIT
CHAR 0, 0
END 0
LABEL 20
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "旦那様。お城から今年の"
LINE_FEED
MESSAGE "給付金が届いてますよ。"
LINE_FEED
MESSAGE "大切に使いましょうねっ。"
KEY_WAIT
END 0
LABEL 21
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "今のお嬢様の体形では、"
LINE_FEED
MESSAGE "少々きついようですね。"
KEY_WAIT
MESSAGE "……着替えていただきます。"
KEY_WAIT
END 0
LABEL 22
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 2673
MESSAGE "えー、きつくないもん。"
LINE_FEED
MESSAGE "頑張ればきられるもん…"
LINE_FEED
MESSAGE "パパわたし太ってるの？"
KEY_WAIT
END 0
LABEL 23
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 2637
MESSAGE "あーん。"
LINE_FEED
MESSAGE "私ってそんなに太っちゃったの！"
LINE_FEED
MESSAGE "どうしよう…"
KEY_WAIT
END 0
LABEL 24
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 2606
MESSAGE "ああっ…"
LINE_FEED
MESSAGE "私ったらいつのまに太っちゃった"
LINE_FEED
MESSAGE "のかしら…"
KEY_WAIT
END 0
LABEL 25
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "宿屋のファットマンさんが"
LINE_FEED
MESSAGE "アルバイトを募集している"
LINE_FEED
MESSAGE "ようです。"
KEY_WAIT
END 0
LABEL 26
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "魔界の店が追加されました。"
LINE_FEED
MESSAGE "Ｓｈｏｐから買い物ができます。"
KEY_WAIT
END 0