LABEL 0
FLAG 478, 1
BG 131
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3564
MESSAGE "モグモグ……"
LINE_FEED
MESSAGE "パパ、このお団子おいしいよ。"
LINE_FEED
MESSAGE "一緒に食べようよ㍍"
SELECT 3, 1, "風流を教える", 2, "団子をもらう", 3, "くつろぐ"
LABEL 1
FLAG 479, 1
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3565
MESSAGE "えっ、食べてばかりいないで"
LINE_FEED
MESSAGE "お花も見ろって？"
KEY_WAIT
FACE 0
VOICE 3566
MESSAGE "だってー、お花はキレイだけど"
LINE_FEED
MESSAGE "食べられないからなぁ。"
KEY_WAIT
FACE 1
VOICE 3567
MESSAGE "それより団子だよ、パパ㍍"
LINE_FEED
MESSAGE "ねっ、ねっ？"
END 0
LABEL 2
FLAG 480, 1
VOICE 3568
MESSAGE "ウフフ、はい、パパ。"
LINE_FEED
MESSAGE "まだまだいっぱいあるからね。"
KEY_WAIT
FACE 4
VOICE 3569
MESSAGE "あっ、一度にほおばったら"
LINE_FEED
MESSAGE "ノドにつかえちゃうよー㍍"
KEY_WAIT
FACE 5
VOICE 3570
MESSAGE "え？　急がないと私が全部"
LINE_FEED
MESSAGE "食べちゃうから、ですって？"
LINE_FEED
MESSAGE "そんな事ないもん！　べーだ！"
END 1
LABEL 3
FLAG 481, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3571
MESSAGE "あはは。パパ、食べてすぐ"
LINE_FEED
MESSAGE "寝たら牛さんになっちゃうよ。"
KEY_WAIT
FACE 4
VOICE 3572
MESSAGE "えーっ、パパったら"
LINE_FEED
MESSAGE "本当に寝るの～㌍"
KEY_WAIT
VOICE 3573
MESSAGE "ねぇっ、パパったら。"
LINE_FEED
MESSAGE "寝てないで遊ぼうよ、"
LINE_FEED
MESSAGE "ねぇねぇっ！"
END 2
LABEL 4
FLAG 482, 1
BG 132
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3574
MESSAGE "んしょ、んしょ……"
LINE_FEED
MESSAGE "あったー！"
KEY_WAIT
VOICE 3575
MESSAGE "ほらっ、見てパパ！"
LINE_FEED
MESSAGE "ひとつ、ふたつ……あはっ、"
LINE_FEED
MESSAGE "これでちょうど１０個目よー！"
SELECT 3, 5, "ほめる", 6, "まだまだ", 7, "大きな貝を見せる"
LABEL 5
FLAG 483, 1
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 3576
MESSAGE "エヘヘ、すごいでしょ？"
LINE_FEED
MESSAGE "パパのために頑張ったよ㍍"
KEY_WAIT
FACE 1
VOICE 3577
MESSAGE "今晩は貝のお料理だねっ。"
LINE_FEED
MESSAGE "キューブにお願いしなくちゃ。"
LINE_FEED
MESSAGE "ふふふ……"
END 0
LABEL 6
FLAG 484, 1
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3578
MESSAGE "あーっ！　パパ、そんなに"
LINE_FEED
MESSAGE "たくさん採ったの㌍"
KEY_WAIT
FACE 7
VOICE 3579
MESSAGE "私より全然多いよ～！"
LINE_FEED
MESSAGE "うう……いっぱい採ったと"
LINE_FEED
MESSAGE "思ったんだけどなぁ。"
KEY_WAIT
FACE 1
VOICE 3580
MESSAGE "こうなったら、もっといっぱい"
LINE_FEED
MESSAGE "見つけるんだから！"
LINE_FEED
MESSAGE "負けないよー！"
END 1
LABEL 7
FLAG 485, 1
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3581
MESSAGE "うわーっ、大きい～！"
LINE_FEED
MESSAGE "そんな大きな貝もいるんだね！"
KEY_WAIT
FACE 0
VOICE 3582
MESSAGE "すごいなぁ。海っていろんな"
LINE_FEED
MESSAGE "生き物がいるのね。私、もっと"
LINE_FEED
MESSAGE "いろいろ知りたいなぁ……"
END 2
LABEL 8
FLAG 486, 1
BG 133
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3583
MESSAGE "ねえ、まだぁ？"
LINE_FEED
MESSAGE "まだお魚かからないの～？"
KEY_WAIT
FACE 0
VOICE 3584
MESSAGE "釣りって思ってたよりずっと"
LINE_FEED
MESSAGE "難しいよ～　パパぁ、どうすれば"
LINE_FEED
MESSAGE "お魚さん釣れてくれるのかなあ？"
SELECT 3, 9, "エサを変える", 10, "放っておく", 11, "交代する"
LABEL 9
FLAG 487, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3585
MESSAGE "そっか。同じエサじゃお魚さんも"
LINE_FEED
MESSAGE "飽きちゃうものね！"
KEY_WAIT
FACE 1
VOICE 3586
MESSAGE "さすがパパ、頭いい㍍"
LINE_FEED
MESSAGE "やってみるね！"
END 0
LABEL 10
FLAG 488, 1
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3587
MESSAGE "えーっ、辛抱が足りない？"
LINE_FEED
MESSAGE "パパの意地悪、助けてくれても"
LINE_FEED
MESSAGE "いいのに～"
KEY_WAIT
FACE 0
VOICE 3588
MESSAGE "いいよーだ。だったら私一人で"
LINE_FEED
MESSAGE "がんばっちゃうもん。お魚さん"
LINE_FEED
MESSAGE "釣れても見せてあげないんだから！"
END 1
LABEL 11
FLAG 489, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3589
MESSAGE "わあ、やってみせてくれるの？"
LINE_FEED
MESSAGE "はい、じゃあ、交代！"
KEY_WAIT
FACE 1
VOICE 3590
MESSAGE "パパ、頑張ってね㍍"
KEY_WAIT
FACE 0
MESSAGE "………………"
LINE_FEED
MESSAGE "…………"
KEY_WAIT
FACE 1
VOICE 3591
MESSAGE "あっ！　かかった！　釣れたよ！"
LINE_FEED
MESSAGE "パパ、すごいすごい！"
END 2
LABEL 12
FLAG 490, 1
BG 134
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3592
MESSAGE "ハーッ、ハーーッ。"
LINE_FEED
MESSAGE "さ、寒い……"
KEY_WAIT
VOICE 3593
MESSAGE "パパーっ、早くーっ。"
LINE_FEED
MESSAGE "朝お散歩するって言ったの"
LINE_FEED
MESSAGE "パパなのに。"
KEY_WAIT
FACE 1
VOICE 3594
MESSAGE "やっと出てきた。"
LINE_FEED
MESSAGE "さ、行こっ、パパ㍍"
KEY_WAIT
FACE 0
VOICE 3595
MESSAGE "冬の山って一面真っ白で、"
LINE_FEED
MESSAGE "きれいだけどなんか怖いな……"
SELECT 3, 13, "一緒に眺める", 14, "手をにぎる", 15, "コートをかけてやる"
LABEL 13
FLAG 491, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3596
MESSAGE "え？　……ううん。"
LINE_FEED
MESSAGE "もう怖くないよ。"
LINE_FEED
MESSAGE "……パパが一緒だもん。"
KEY_WAIT
VOICE 3597
MESSAGE "ねえ、パパ。"
LINE_FEED
MESSAGE "私から離れないでね……"
END 0
LABEL 14
FLAG 492, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3598
MESSAGE "きゃ！"
LINE_FEED
MESSAGE "……うふふ、パパの手も冷たい。"
KEY_WAIT
VOICE 3599
MESSAGE "冷たくて寒いけど、この"
LINE_FEED
MESSAGE "透き通った空気……"
LINE_FEED
MESSAGE "私、好きだなぁ……"
END 1
LABEL 15
FLAG 493, 1
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 3600
MESSAGE "あっ……"
LINE_FEED
MESSAGE "ありがとう。暖かいよ……"
KEY_WAIT
FACE 3
VOICE 3601
MESSAGE "でも、それだとパパが寒くない？"
LINE_FEED
MESSAGE "ごめんね、パパ……"
END 2