LABEL 0
FLAG 1715, 1
BG 0
CHAR 0, 1
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 2735
MESSAGE "ねえねえ、パパ。\n今日のあさごはんって\nパパが作ったの？"
KEY_WAIT
CHAR 0, 5
FACE 4
VOICE 2736
MESSAGE "ふえぇ、すごいなぁ。"
KEY_WAIT
CHAR 0, 1
FACE 0
VOICE 2737
MESSAGE "パパがお料理できるなんて\nしらなかったなぁ。"
KEY_WAIT
CHAR 0, 5
FACE 4
VOICE 2738
MESSAGE "え？　そんなにたいしたものが\nできるわけじゃない？"
KEY_WAIT
CHAR 0, 1
FACE 0
VOICE 2739
MESSAGE "でもぉ、このスープとか\nおいしそうだよ。"
KEY_WAIT
VOICE 2740
MESSAGE "へぇ～、\n昔、冒険してたときにおともだちに\n教えてもらったんだぁ……"
KEY_WAIT
VOICE 2741
MESSAGE "あ、うん、あんまり話してたら\nさめちゃうもんね。"
KEY_WAIT
VOICE 2742
MESSAGE "それじゃあ……"
KEY_WAIT
CHAR 0, 2
FACE 1
VOICE 2743
MESSAGE "いっただきま～す。"
KEY_WAIT
OFF_CHAR 3
OFF_FACE_WINDOW
FACE 65535
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
BG 265
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 2744
MESSAGE "……はむはむ。\nパパぁ、これおぃひいよぉ。"
KEY_WAIT
FACE 0
VOICE 2745
MESSAGE "……わたし、\nキューブの作ってくれる\nごはんも好きだけど……"
KEY_WAIT
FACE 1
VOICE 2746
MESSAGE "パパが作ってくれたごはんも\n大好き♪"
KEY_WAIT
FACE 0
VOICE 2747
MESSAGE "あ、パパ。\nこれおかわりある？"
KEY_WAIT
VOICE 2748
MESSAGE "うん、ちょーだい。"
KEY_WAIT
VOICE 2749
MESSAGE "はむはむ、はむはむ。"
KEY_WAIT
FACE 0
VOICE 2750
MESSAGE "……っ㌍"
KEY_WAIT
VOICE 2751
MESSAGE "けほっ、けほっ㌍"
KEY_WAIT
FACE 6
VOICE 2752
MESSAGE "……えへへ、つっかえちゃった。"
KEY_WAIT
FACE 3
VOICE 2753
MESSAGE "落ち着いて食べなさい？\nはーい、ごめんなさーい。"
KEY_WAIT
OFF_FACE_WINDOW
FACE 65535
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
BG 176
MESSAGE "　　　　　　　　・　　　　　　　\n　　　　　　　　・　　　　　　　\n　　　　　　　　・　　　　　　　"
KEY_WAIT
OFF_FACE_WINDOW
FACE 65535
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
BG 265
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 2754
MESSAGE "ごちそうさまー！"
KEY_WAIT
FACE 0
VOICE 2755
MESSAGE "はふぅ、おなかいっぱいだよ。"
KEY_WAIT
FACE 5
VOICE 2756
MESSAGE "ん？　どうしたの、パパ。\nわたしの顔になにかついてる？"
KEY_WAIT
FACE 7
VOICE 2757
MESSAGE "え？　お口のまわりがよごれてる？\nあうぅ……ふかないと。"
SELECT 2, 1, "口元をふいてあげる", 2, "顔を洗ってきなさい"
LABEL 1
SE_STOP
END 0
LABEL 2
SE_STOP
BG 0
END 1