LABEL 0
FACE 28
MESSAGE_NAME "キューブ"
MESSAGE "あの、旦那様。申し上げにくい\n事なのですが、バカンスに行くため\nには養育費が足りないようです……"
KEY_WAIT
MESSAGE "お嬢様にはおかわいそうですが、\nここは別の方法でお休みを取って\nいただくしか……はい……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 1
FACE 65535
OFF_FACE_WINDOW
MESSAGE "生活費が３０Ｇかかります。"
KEY_WAIT
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 2
FACE 65535
OFF_FACE_WINDOW
MESSAGE "生活費が８０Ｇかかります。"
KEY_WAIT
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 3
FACE 65535
OFF_FACE_WINDOW
MESSAGE "生活費が１０Ｇかかります。"
KEY_WAIT
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 4
FACE 65535
OFF_FACE_WINDOW
MESSAGE "生活費が５Ｇかかります。"
KEY_WAIT
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 5
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "セーブ、ロード、オプションの\n設定ができます。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 6
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "道具や武器、洋服、\n食事、教会、病院など\n生活に必要なお店にいけます。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 7
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "お嬢様と特定の話題を\nお話することができます。"
KEY_WAIT
FACE 26
MESSAGE "お嬢様のお健やかな成長のためにも\n旦那様の方からお話される機会を\n持たれるのがよろしいでしょう。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 8
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "道具を使ったり\n服を着替えることができます。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 9
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "現在は「無理はさせない」に\n設定されています。\nどうなさいますか？"
END 0
LABEL 10
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "現在は「活発に育てる」に\n設定されています。\nどうなさいますか？"
END 0
LABEL 11
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "現在は「おしとやかに育てる」に\n設定されています。\nどうなさいますか？"
END 0
LABEL 12
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "現在は「ダイエットさせる」に\n設定されています。\nどうなさいますか？"
END 0
LABEL 13
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "かしこまりました。\n月々の生活費が３０Ｇかかります。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 14
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "かしこまりました。\n月々の生活費が８０Ｇかかります。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 15
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "かしこまりました。\n月々の生活費が１０Ｇかかります。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 16
FACE 23
MESSAGE_NAME "キューブ"
MESSAGE "かしこまりました。\n月々の生活費が５Ｇかかります。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 17
MESSAGE "触れたい場所をタッチして下さい。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 18
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 3782
MESSAGE "えへへ、なでてもらっちゃったぁ～\nパパの手ってあったかいねぇ～。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 19
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3783
MESSAGE "ふぁふぁ、らいふき～㍍"
KEY_WAIT
FACE 1
VOICE 3784
MESSAGE "あははは。おもしろーい！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 20
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3785
MESSAGE "ん？　どうしたのパパ？\n別にどこも悪くないよ？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 21
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3786
MESSAGE "ん？　パパなになに？"
KEY_WAIT
FACE 1
VOICE 3787
MESSAGE "抱っこしてくれるの？　わーい！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 22
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 3788
MESSAGE "あははは。くすぐったいよぉ～。\nもう、やめてってばー。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 23
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 3789
MESSAGE "うー。あんまり頭触らないでー。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 24
FACE 8
MESSAGE_NAME "[娘の名前]"
VOICE 3790
MESSAGE "あによぅ～。\nわらひが何かしたって言うの～？"
KEY_WAIT
FACE 2
VOICE 3791
MESSAGE "もう、わたしで遊ばないでっ！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 25
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3792
MESSAGE "別にどこも悪くありませ～ん。\n今ごろ気にしたって遅いんだから…"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 26
FACE 5
MESSAGE_NAME "[娘の名前]"
VOICE 3793
MESSAGE "今日はそういう気分じゃないのっ！\n抱っこなんかされたって、\n嬉しくないもん。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 27
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3794
MESSAGE "あははは。ぱ、パパったら、\nちょ、ちょっとやめてってば～。"
KEY_WAIT
FACE 2
VOICE 3795
MESSAGE "やめてって、言ってるでしょ。\nいい加減にしてよ！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 28
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3796
MESSAGE "ありがとう、パパ。\n私、大丈夫だよ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 29
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3797
MESSAGE "顔色悪いよね……。"
KEY_WAIT
VOICE 3798
MESSAGE "大丈夫だから、\nあんまり悲しそうにしないで……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 30
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3799
MESSAGE "うん……ちょっとつらいかも……。\nもう少し、こうしてて欲しいな……"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 31
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3800
MESSAGE "ありがとう……\nパパ……　あったかい。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 32
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3801
MESSAGE "ありがとう、パパ。\nちょっと楽になったよ……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 33
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 3802
MESSAGE "うふふ、ありがとうお父さん。\n大好きっ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 34
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 3803
MESSAGE "んもう～。お父さんったら～。\nいつまでも子供じゃないんだから、\nそういうの、やめてよ～。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 35
FACE 5
MESSAGE_NAME "[娘の名前]"
VOICE 3804
MESSAGE "ちょ、ちょっと、お父さんったら～\nどこ、触ってるのよ、もう……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 36
FACE 3
MESSAGE_NAME "[娘の名前]"
VOICE 3805
MESSAGE "う～ん、お父さんも気になる？\nダイエットしたほうがいいのかな？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 37
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 3806
MESSAGE "あははは。お父さんったら、\nちょっと、くすぐったいってば～。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 38
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3807
MESSAGE "……なによ？"
KEY_WAIT
VOICE 3808
MESSAGE "いつまでも子供じゃないんだから、\nそんなことしたって、無駄よ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 39
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3809
MESSAGE "ちょ、ちょっと\nあんまり引っ張らないでよ……"
KEY_WAIT
VOICE 3810
MESSAGE "痛いってば…"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 40
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3811
MESSAGE "お父さんっ！　どこ触ってるの！\nもうっ、信じられないっ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 41
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3812
MESSAGE "なにかしら？　お父さん？"
KEY_WAIT
VOICE 3813
MESSAGE "もう子供じゃありませんの。\nそういうので喜ぶ歳でもないわ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 42
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3814
MESSAGE "さっきからずいぶんと熱心だけど…"
KEY_WAIT
VOICE 3815
MESSAGE "お父さんってそういうの好きなの？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 43
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3816
MESSAGE "えへへ、ありがとう、お父さん。\nちょっと元気でたかも……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 44
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3817
MESSAGE "あはは…。ごめんね、お父さん、\n心配かけちゃって……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 45
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3818
MESSAGE "うーん、ちょっと苦しい……。\nつらいなぁ……。"
KEY_WAIT
VOICE 3819
MESSAGE "そうやってさすってもらえると\nちょっと楽かも……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 46
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3820
MESSAGE "お父さん、温かい……。\nなんか、小さい頃思い出すね……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 47
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3821
MESSAGE "お父さん、心配かけて\nごめんなさい。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 48
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3823
MESSAGE "ふふっ。\nお父様、私もいつまでも子供じゃ\nありませんわ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
VOICE 3824
MESSAGE "でも、気遣ってくれて……\nありがとう……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 49
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3825
MESSAGE "お父様の手、温かい……。\n仕事も勉強も頑張らないと\nいけませんわね。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 50
FACE 6
MESSAGE_NAME "[娘の名前]"
VOICE 3826
MESSAGE "お父様っ、どこ触ってるんですか。\nそういうの困りますっ。"
KEY_WAIT
VOICE 3827
MESSAGE "もう…、お父様のエッチ……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 51
FACE 7
MESSAGE_NAME "[娘の名前]"
VOICE 3828
MESSAGE "最近、腰がつらくてね……。"
KEY_WAIT
FACE 4
VOICE 3829
MESSAGE "って、そんな年じゃありませんっ。\nお気持ちだけ、ありがたく\n受け取っておきます。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 52
FACE 1
MESSAGE_NAME "[娘の名前]"
VOICE 3830
MESSAGE "あははは。\nちょ、ちょっとそこは……。"
KEY_WAIT
VOICE 3831
MESSAGE "やだもぅ、お父様ったら……\nあんまり触ったら、くすぐったい\nですわ。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 53
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3832
MESSAGE "何ですか？　私、もう子供じゃ\nありませんのよ？"
KEY_WAIT
VOICE 3833
MESSAGE "そういうので喜ぶ歳でも\nないですから。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 54
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3834
MESSAGE "私の顔に何か？"
KEY_WAIT
VOICE 3835
MESSAGE "特に用が無いのであれば\n放っておいて下さい。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 55
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3836
MESSAGE "お父様っ、どこ触ってるんですか！\nいい加減にして下さいっ！"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 56
FACE 4
MESSAGE_NAME "[娘の名前]"
VOICE 3837
MESSAGE "あの…お父様？\nそういうのにご興味がおあり\nですの？"
KEY_WAIT
VOICE 3838
MESSAGE "それでしたら、しかるべき\nお店にでも行ってらしたら\nどうですか？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 57
FACE 2
MESSAGE_NAME "[娘の名前]"
VOICE 3839
MESSAGE "お父様？\n別になんともありませんわ。\nお気遣いなら結構ですから"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 58
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3840
MESSAGE "お父様、もう少しそうして\nもらってもいい？"
KEY_WAIT
VOICE 3841
MESSAGE "ありがとう……。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 59
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3842
MESSAGE "うん、大丈夫だから……\nそんなに心配そうな顔しないで\n私の方が悲しくなってしまいます…"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 60
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3843
MESSAGE "お父様の手…　優しい……。\n不思議ね、なんだか気持ちが\n落ち着いてくる感じ……。"
KEY_WAIT
VOICE 3844
MESSAGE "もう少し、こうしてもらってても\nいいかな？"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 61
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3845
MESSAGE "小さい頃、こうしてもらったのを\n思い出すわ……。"
KEY_WAIT
VOICE 3846
MESSAGE "不思議ですわ。\n少し元気が出てきた気がするもの。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0
LABEL 62
FACE 0
MESSAGE_NAME "[娘の名前]"
VOICE 3847
MESSAGE "お父様、ありがとう……\n気を遣わせてしまって……\nごめんなさいね。"
KEY_WAIT
FACE 65535
OFF_FACE_WINDOW
OFF_FACE_WINDOW
MESSAGE_WINDOW 0
END 0